Repository kubev2v/forklift-console-plugin, pull requests merged in 2022-11, with the labels that each got.

#65 Fix kind download hint
  scripts/configure-kind.sh
Labels: documentation

#74 Change quay repo from kubevirt-ui to kubev2v
  README.md
  deployment/forklift-console-plugin/values.yaml
  docs/helm.md
  docs/podman.md
Labels: documentation

#75 Update the branch used as default image in helm
  deployment/forklift-console-plugin/values.yaml
Labels: documentation

#76 Pagination for StandardPage component
  src/components/StandardPage/StandardPage.tsx
  src/components/TableView/TableView.tsx
Labels: kind/feature

#82 Consolidate plugin extension modules
  console-extensions.ts
  locales/en/plugin__forklift-console-plugin.json
  plugin.ts
  src/modules/Hosts/dynamic-plugin.ts
  src/modules/Mappings/dynamic-plugin.ts
  src/modules/Plans/VMMigrationDetailsWrapper.tsx
  src/modules/Plans/dynamic-plugin.ts
  src/modules/Providers/HostsPageWrapper.tsx
  src/modules/Providers/dynamic-plugin.ts
  src/modules/VmMigrationDetails/dynamic-plugin.ts
  tsconfig.json
Labels: kind/cleanup

#81 Use upstream namespace as default value for webpack
  webpack.config.ts
Labels: kind/cleanup

#33 Convert Providers screen to Console page
  jest.config.ts
  locales/en/plugin__forklift-console-plugin.json
  pkg/web/src/app/Providers/HostsPage.tsx
  pkg/web/src/app/Providers/components/ProvidersTable/ProviderActionsDropdown.tsx
  src/components/ActionServiceDropdown.tsx
  src/components/Filter/helpers.ts
  src/components/types.ts
  src/modules/Providers/ProviderRow.tsx
  src/modules/Providers/ProvidersPage.tsx
  src/modules/Providers/ProvidersWrapper.tsx
  src/modules/Providers/UseMergedProviders.ts
  src/modules/Providers/__tests__/mergeData.test.ts
  src/modules/Providers/__tests__/mergedMockData.json
  src/modules/Providers/data.ts
  src/modules/Providers/dynamic-plugin.ts
  src/modules/Providers/index.ts
  src/modules/Providers/providerActions.tsx
  src/utils/constants.ts
  src/utils/enums.ts
  src/utils/fetch.ts
  src/utils/types.ts
Labels: kind/feature

#88 Rename .stylelintrc.yaml to .stylelintrc.yml
  .stylelintrc.yml
  locales/en/plugin__forklift-console-plugin.json
Labels: kind/bug

#92 Update docs
  Containerfile
  Containerfile.dev
  README.md
  deployment/forklift-console-plugin/templates/consoleplugin.tpl
  docs/README.md
  docs/cli-tools.md
  docs/container-images.md
  docs/create-dev-token.md
  docs/develop-remote.md
  docs/develop-with-crc.md
  docs/develop-with-kind.md
  docs/development-server.md
  docs/helm.md
  docs/i18n.md
  docs/linting.md
  docs/openshift-console.md
  docs/podman.md
  docs/using-local-registry.md
  package.json
  scripts/README.md
  scripts/clean-cluster.sh
  scripts/configure/k8s.sh
  scripts/configure/openshift.sh
  scripts/deploy-cluster.sh
  scripts/entrypoint.dev.sh
  scripts/start-console.sh
  scripts/welcome.dev.txt
  scripts/yaml/crds/console.openshift.io_consoleplugins.yaml
  scripts/yaml/crds/console.openshift.io_consolequickstarts.yaml
  scripts/yaml/crds/console.openshift.io_consoleyamlsamples.yaml
  scripts/yaml/forklift-plugin-dev.tpl.yaml
  scripts/yaml/forklift-plugin-dev.yaml
Labels: documentation

#95 Check for host provider type, not just url
  src/modules/Providers/ProviderRow.tsx
  src/modules/Providers/providerActions.tsx
Labels: kind/bug
