Repository kubev2v/forklift-console-plugin, pull requests merged in 2023-10, with the labels that each got.

#747 Add date filter
  packages/common/src/components/Filter/DateFilter.tsx
  packages/common/src/components/Filter/index.ts
  packages/common/src/components/FilterGroup/matchers.ts
  packages/common/src/utils/__tests__/dates.test.ts
  packages/common/src/utils/dates.ts
  packages/common/src/utils/index.ts
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/__mocks__/console_components.tsx
  packages/forklift-console-plugin/src/modules/Plans/PlanRow.tsx
  packages/forklift-console-plugin/src/modules/Plans/PlansPage.tsx
  packages/forklift-console-plugin/src/modules/Plans/__tests__/__snapshots__/PlanRow.test.tsx.snap
  packages/forklift-console-plugin/src/modules/Plans/__tests__/mergedMockData.json
Labels: kind/feature

#756 Emphasis VDDK only accelerates migrations
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderVDDKImage/EditProviderVDDKImage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/VSphereProviderCreateForm.tsx
Labels: kind/cleanup

#758 [MTV-712] bump msw
  package-lock.json
  packages/mocks/package.json
Labels: bug

#759 [v2.5.2] [MTV-712] bump msw
  package-lock.json
  packages/mocks/package.json
Labels: bug

#760 Add missing workd to cspell
  packages/eslint-plugin/cspell.wordlist.txt
Labels: kind/cleanup

#761 Bump nginx version
  build/Containerfile
Labels: kind/cleanup
