Repository kubev2v/forklift-console-plugin, pull requests merged in 2023-06, with the labels that each got.

#466 Extend host secrets with data for verification
  packages/legacy/src/queries/hosts.ts
  packages/legacy/src/queries/types/secrets.types.ts
Labels: kind/cleanup

#467 Add optional notifications on top of the list page view
  packages/forklift-console-plugin/src/components/page/StandardPage.tsx
Labels: kind/feature

#468 Dont use packstack in readme example
  README.md
Labels: kind/cleanup

#473 Add INVENTORY_SERVER_HOST example to readme file
  README.md
Labels: documentation

#475 Update types and mocks
  config/cspell.wordlist.txt
  packages/mocks/src/definitions/basic/disks.mock.ts
  packages/mocks/src/definitions/basic/mappings.mock.ts
  packages/mocks/src/definitions/basic/namespaces.mock.ts
  packages/mocks/src/definitions/basic/networks.mock.ts
  packages/mocks/src/definitions/basic/nicProfiles.mock.ts
  packages/mocks/src/definitions/basic/providers.mock.ts
  packages/mocks/src/definitions/basic/storages.mock.ts
  packages/mocks/src/definitions/basic/tree.mock.ts
  packages/mocks/src/definitions/basic/vms.mock.ts
  packages/mocks/src/definitions/utils.ts
  packages/types/src/index.ts
  packages/types/src/models/index.ts
  packages/types/src/types/InventoryByType.ts
  packages/types/src/types/host/index.ts
  packages/types/src/types/index.ts
  packages/types/src/types/k8s/V1NetworkAttachmentDefinition.ts
  packages/types/src/types/k8s/V1Secret.ts
  packages/types/src/types/k8s/index.ts
  packages/types/src/types/provider/base/index.ts
  packages/types/src/types/provider/index.ts
  packages/types/src/types/provider/openshift/Namespace.ts
  packages/types/src/types/provider/openshift/NetworkAttachmentDefinition.ts
  packages/types/src/types/provider/openshift/Provider.ts
  packages/types/src/types/provider/openshift/Resource.ts
  packages/types/src/types/provider/openshift/StorageClass.ts
  packages/types/src/types/provider/openshift/index.ts
  packages/types/src/types/provider/openstack/Network.ts
  packages/types/src/types/provider/openstack/Provider.ts
  packages/types/src/types/provider/openstack/Resource.ts
  packages/types/src/types/provider/openstack/TreeNode.ts
  packages/types/src/types/provider/openstack/VM.ts
  packages/types/src/types/provider/openstack/VolumeType.ts
  packages/types/src/types/provider/openstack/index.ts
  packages/types/src/types/provider/ovirt/Cluster.ts
  packages/types/src/types/provider/ovirt/Disk.ts
  packages/types/src/types/provider/ovirt/DiskProfile.ts
  packages/types/src/types/provider/ovirt/Host.ts
  packages/types/src/types/provider/ovirt/Network.ts
  packages/types/src/types/provider/ovirt/NicProfile.ts
  packages/types/src/types/provider/ovirt/Provider.ts
  packages/types/src/types/provider/ovirt/Resource.ts
  packages/types/src/types/provider/ovirt/StorageDomain.ts
  packages/types/src/types/provider/ovirt/TreeNode.ts
  packages/types/src/types/provider/ovirt/VM.ts
  packages/types/src/types/provider/ovirt/index.ts
  packages/types/src/types/provider/ovirt/model.ts
  packages/types/src/types/provider/vsphere/DataStore.ts
  packages/types/src/types/provider/vsphere/Network.ts
  packages/types/src/types/provider/vsphere/Provider.ts
  packages/types/src/types/provider/vsphere/Resource.ts
  packages/types/src/types/provider/vsphere/TreeNode.ts
  packages/types/src/types/provider/vsphere/VM.ts
  packages/types/src/types/provider/vsphere/index.ts
  packages/types/src/types/provider/vsphere/model.ts
  packages/types/src/types/secret/index.ts
Labels: kind/cleanup

#478 Add missing common providers inventory type
  packages/types/src/types/ProviderInventory.ts
  packages/types/src/types/index.ts
Labels: kind/cleanup

#479 Ignore spelling in mocks
  packages/mocks/src/definitions/basic/hooks.mock.ts
  packages/mocks/src/definitions/basic/mustGather.mock.ts
  packages/mocks/src/definitions/basic/plans.mock.ts
Labels: kind/cleanup

#480 Ignore spelling in mocks ii
  packages/mocks/src/definitions/basic/secrets.mock.ts
  packages/mocks/src/definitions/basic/storages.mock.ts
  packages/mocks/src/definitions/basic/vms.mock.ts
Labels: kind/cleanup

#487 Change node files to use .cjs
  cypress/.prettierrc.cjs
  packages/common/.eslintrc.cjs
  packages/common/.prettierrc.cjs
  packages/eslint-plugin/.eslintrc.cjs
  packages/eslint-plugin/.prettierrc.cjs
  packages/forklift-console-plugin/.eslintrc.cjs
  packages/forklift-console-plugin/.prettierrc.cjs
  packages/legacy/.eslintignore
  packages/legacy/.eslintrc.cjs
  packages/legacy/package.json
  packages/mocks/.eslintrc.cjs
  packages/mocks/.prettierrc.cjs
  packages/types/.eslintrc.cjs
  packages/types/.prettierrc.cjs
  packages/webpack/.eslintrc.cjs
  packages/webpack/.prettierrc.cjs
Labels: kind/cleanup

#488 Remove un used rollup node resolver
  config/rollup.base.js
  package-lock.json
  package.json
Labels: kind/cleanup

#489 Add missing paths to tscofig of main app
  packages/forklift-console-plugin/tsconfig.json
Labels: kind/cleanup

#490 Move cypress config to cyress dir
  .github/workflows/on-pull-request.yaml
  cypress/cypress.config.cjs
  cypress/tsconfig.json
  package.json
  packages/common/.stylelintrc.yml
  packages/eslint-plugin/stylelintrc.yml
  packages/forklift-console-plugin/.stylelintrc.yml
  packages/types/.stylelintrc.yml
  packages/webpack/.stylelintrc.yml
Labels: kind/cleanup

#491 move rollup to build package
  cypress/tsconfig.json
  packages/build/src/metadata.js
  packages/build/src/rollup.base.js
  packages/build/src/rollup/plugin-har.js
  packages/build/src/rollup/plugin-write-json-file.js
  packages/build/src/tsconfig.base.json
  packages/common/tsconfig.json
  packages/forklift-console-plugin/tsconfig.json
  packages/legacy/tsconfig.json
  packages/mocks/rollup.config.js
  packages/mocks/tsconfig.json
  packages/types/rollup.config.js
  packages/types/tsconfig.json
  packages/webpack/rollup.config.js
  packages/webpack/tsconfig.json
Labels: kind/cleanup

#493 Use rollup for common package
  packages/common/package.json
  packages/common/rollup.config.js
  packages/common/src/index.ts
  packages/forklift-console-plugin/src/components/mappings/MappingPage.tsx
  packages/forklift-console-plugin/src/components/mappings/MappingRow.tsx
  packages/forklift-console-plugin/src/components/mappings/mappingActions.tsx
  packages/forklift-console-plugin/src/components/page/ManageColumnsToolbar.tsx
  packages/forklift-console-plugin/src/components/page/StandardPage.tsx
  packages/forklift-console-plugin/src/components/page/__tests__/StandardPage.test.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/EmptyStateNetworkMaps.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/NetworkMappingRow.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/NetworkMappingsPage.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/NetworkMappingsWrapper.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/__tests__/MappingRow.test.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/mappingActions.tsx
  packages/forklift-console-plugin/src/modules/Plans/EmptyStatePlans.tsx
  packages/forklift-console-plugin/src/modules/Plans/PlanRow.tsx
  packages/forklift-console-plugin/src/modules/Plans/PlanWizardWrapper.tsx
  packages/forklift-console-plugin/src/modules/Plans/PlansPage.tsx
  packages/forklift-console-plugin/src/modules/Plans/PlansWrapper.tsx
  packages/forklift-console-plugin/src/modules/Plans/VMMigrationDetailsWrapper.tsx
  packages/forklift-console-plugin/src/modules/Plans/__tests__/PlanRow.test.tsx
  packages/forklift-console-plugin/src/modules/Plans/planActions.tsx
  packages/forklift-console-plugin/src/modules/Providers/AddProviderButton.tsx
  packages/forklift-console-plugin/src/modules/Providers/HostsPageWrapper.tsx
  packages/forklift-console-plugin/src/modules/Providers/ProviderRow.tsx
  packages/forklift-console-plugin/src/modules/Providers/ProviderRow/HostCell.tsx
  packages/forklift-console-plugin/src/modules/Providers/ProviderRow/StatusCell.tsx
  packages/forklift-console-plugin/src/modules/Providers/ProviderRow/TextCell.tsx
  packages/forklift-console-plugin/src/modules/Providers/ProviderRow/TypeCell.tsx
  packages/forklift-console-plugin/src/modules/Providers/ProviderRow/types.ts
  packages/forklift-console-plugin/src/modules/Providers/ProvidersPage.tsx
  packages/forklift-console-plugin/src/modules/Providers/ProvidersWrapper.tsx
  packages/forklift-console-plugin/src/modules/Providers/providerActions.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/EmptyStateStorageMaps.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/StorageMappingRow.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/StorageMappingsPage.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/StorageMappingsWrapper.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/__tests__/MappingRow.test.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/mappingActions.tsx
  packages/forklift-console-plugin/src/utils/enums.ts
Labels: kind/cleanup

#494 Add readme files for packages
  packages/build/README.md
  packages/eslint-plugin/README.md
  packages/mocks/README.md
Labels: documentation

#500 Disable eslint any warning on legacy common types
  packages/legacy/src/queries/types/common.types.ts
Labels: kind/cleanup

#501 Fix typos from #499
  ci/deploy-console.sh
  ci/yaml/okd-console-tls.yaml
Labels: kind/cleanup

#503 Move OKD_CONSOLE_YAML env var to github workflows
  .github/workflows/on-pull-request.yaml
  package.json
Labels: kind/cleanup

#505 link and page styling tweaks
  packages/common/src/components/ExternalLink/ExternalLink.tsx
  packages/forklift-console-plugin/src/components/page/StandardPage.style.css
  packages/forklift-console-plugin/src/components/page/StandardPage.tsx
  packages/forklift-console-plugin/src/components/page/__tests__/__snapshots__/StandardPage.test.tsx.snap
Labels: kind/cleanup

#509 Add k8s common and condition types to index file
  packages/types/src/types/k8s/index.ts
  packages/types/src/types/provider/openshift/VM.ts
Labels: kind/cleanup

#510 Move vsphere host type into the provider dir
  packages/mocks/src/definitions/basic/hosts.mock.ts
  packages/mocks/src/definitions/utils.ts
  packages/types/src/types/index.ts
  packages/types/src/types/provider/vsphere/Host.ts
  packages/types/src/types/provider/vsphere/host/VSphereHostInventory.ts
  packages/types/src/types/provider/vsphere/host/index.ts
Labels: kind/cleanup

#512 Rename ProvidersInventory to ProvidersInventoryList
  packages/mocks/src/definitions/basic/providers.mock.ts
  packages/mocks/src/definitions/utils.ts
  packages/types/src/types/Modify.ts
  packages/types/src/types/ProvidersInventoryList.ts
  packages/types/src/types/index.ts
Labels: kind/cleanup
