Repository kubev2v/forklift-console-plugin, pull requests merged in 2023-08, with the labels that each got.

#650 Re-enable mock console extension
  packages/forklift-console-plugin/src/__mock-console-extension/dynamic-plugin.ts
  packages/mocks/src/definitions/basic/hosts.mock.ts
  packages/mocks/src/definitions/basic/paths.ts
Labels: kind/bug

#654 Refactor the hooks used on the details page tabs
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Credentials/ProviderCredentials.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/ProviderHosts.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Networks/ProviderNetworks.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/ProviderVirtualMachines.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/YAML/ProviderYAML.tsx
Labels: kind/bug

#655 Allow urls to start with numbers
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/__tests__/common.test.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/common.ts
Labels: kind/bug

#660 Change the storage mapping for OVA
  packages/legacy/src/queries/storages.ts
Labels: kind/feature

#661 Remove unneeded dot after link
  packages/forklift-console-plugin/src/modules/Providers/utils/components/DetailsPage/DetailItem.tsx
Labels: kind/bug

#662 Put vsphere product name above numeric values
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/InventorySection/VSphereInventorySection.tsx
Labels: kind/bug

#663 Add permissions to the depenedencie of vmware host list
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/VSphereHostsList.tsx
Labels: kind/bug

#664 Align edit URL forms with the updated help messages
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderDefaultTransferNetwork/EditProviderDefaultTransferNetwork.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderURL/OpenshiftEditURLModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderURL/OpenstackEditURLModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderURL/OvirtEditURLModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderURL/VSphereEditURLModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OVADetailsSection.tsx
Labels: kind/bug

#669 Bump version to 2.5.0
  build/Containerfile
  packages/forklift-console-plugin/package.json
Labels: kind/bug

#671 [MTV-452] Update controller settings help messages
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/cards/SettingsCard.tsx
Labels: kind/bug

#674 Wrap label within TableLinkCell to a new line if needed
  packages/forklift-console-plugin/src/modules/Providers/utils/components/TableCell/TableCell.tsx
  packages/forklift-console-plugin/src/modules/Providers/utils/components/TableCell/TableLabelCell.tsx
  packages/forklift-console-plugin/src/modules/Providers/utils/components/TableCell/TableLinkCell.tsx
Labels: kind/bug

#673 Align create button logic with empty state
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/components/mappings/MappingPage.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/NetworkMappingsPage.tsx
  packages/forklift-console-plugin/src/modules/Plans/PlansPage.tsx
Labels: kind/bug

#675 Add canPatch to plan duplicat action dependencies
  packages/forklift-console-plugin/src/modules/Plans/planActions.tsx
Labels: kind/bug, QE

#679 update plugin version in package lock file
  package-lock.json
Labels: kind/cleanup

#680 Refactor provider critical condition alert
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/ProviderPageHeadings.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/ProvidersListPage.style.css
  packages/forklift-console-plugin/src/modules/Providers/views/list/components/ProviderCriticalCondition.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/components/index.ts
Labels: kind/cleanup

#681 Each provider has differetn storage count, use specific storage count
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/utils/helpers/getValueByJsonPath.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/InventorySection/OVAInventorySection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/ProvidersListPage.tsx
  packages/types/src/types/provider/ova/Provider.ts
Labels: kind/bug

#686 Set OpenShift vm power status in plans wizard
  packages/legacy/src/common/components/VMNameWithPowerState.tsx
  packages/legacy/src/queries/types/vms.types.ts
Labels: kind/bug

#687 Add createdForResourceType labels to secrets created for hosts and pr…
  packages/forklift-console-plugin/src/modules/Providers/views/create/utils/createSecret.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/utils/helpers/onSaveHost.ts
Labels: kind/bug

#692 Set the storage mapping source title for OpenShift
  cypress/e2e/tests/Providers/CreateProvider.cy.ts
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/views/list/components/ProvidersEmptyState.tsx
  packages/legacy/src/Mappings/Mappings.tsx
  packages/legacy/src/common/helpers.ts
Labels: kind/bug

#694 [MTV-556] controller_snapshot_status_check_rate_seconds is polling
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Overview/modal/EditSnapshotPoolingIntervalModal.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/cards/SettingsCard.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/ProvidersListPage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/components/AddProviderButton.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/components/index.ts
Labels: kind/bug

#696 Refactor two provider add buttons to one
  packages/forklift-console-plugin/src/modules/Providers/views/list/ProvidersListPage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/components/AddProviderButton.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/components/ProvidersAddButton.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/components/index.ts
Labels: kind/cleanup

#698 Reorder types list in create provider form
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/providerCardItems.tsx
Labels: kind/bug

#699 Service Account Token to Service Account Bearer Token
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenshiftCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/list/OpenshiftCredentialsList.tsx
Labels: kind/bug

#700 Use sentnece case for form fields
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderVDDKImage/EditProviderVDDKImage.tsx
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/vsphereProviderValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/ProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/VSphereProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenstackCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenstackCredentialsEditFormGroups/ApplicationCredentialNameSecretFieldsFormGroup.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenstackCredentialsEditFormGroups/ApplicationWithCredentialsIDFormGroup.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenstackCredentialsEditFormGroups/TokenWithUsernameSecretFieldsFormGroup.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/list/OpenstackCredentialsList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/VSphereDetailsSection.tsx
Labels: kind/bug

#701 use findByTestId and not findAllByTestId
  cypress/e2e/tests/Providers/CreateProvider.cy.ts
Labels: kind/cleanup

#704 After create redirect to providers namespace
  packages/forklift-console-plugin/src/modules/Providers/views/create/ProvidersCreatePage.tsx
Labels: kind/bug

#707 Move warm migration settings to the bottom
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/cards/SettingsCard.tsx
Labels: kind/bug

#710 Local OCP target can have null or undefined URL, not just empty string
  packages/legacy/src/common/helpers.ts
Labels: kind/bug
