Repository kubev2v/forklift-console-plugin, pull requests merged in 2023-03, with the labels that each got.

#255 Don't block provider form if caCert is missing
  packages/legacy/src/common/constants.ts
Labels: kind/bug

#250 Use openstack tree/project api endpoint
  packages/legacy/src/queries/mocks/tree.mock.ts
  packages/legacy/src/queries/tree.ts
  packages/legacy/src/queries/types/tree.types.ts
Labels: kind/bug

#260 Update disk transfer progress for virt-v2v on EL9
  packages/legacy/src/Plans/components/VMMigrationDetails.tsx
Labels: kind/feature

#265 Add mock data and tests for OpenStack secure connection mode
  packages/forklift-console-plugin/src/modules/Providers/__tests__/__snapshots__/ProviderRow.test.tsx.snap
  packages/forklift-console-plugin/src/modules/Providers/__tests__/mergedMockData.json
  packages/legacy/src/queries/mocks/providers.mock.ts
  packages/legacy/src/queries/mocks/secrets.mock.ts
  packages/legacy/src/queries/secrets.ts
Labels: kind/feature

#266 Rename openstack insecure secret key to insecureSkipVerify
  packages/legacy/src/Providers/components/AddEditProviderModal/helpers.ts
  packages/legacy/src/client/helpers.ts
  packages/legacy/src/queries/mocks/secrets.mock.ts
  packages/legacy/src/queries/types/secrets.types.ts
  packages/types/src/utils/models/ProviderSecrets.ts
Labels: kind/feature

#282 Check at runtime if data to be filtered is an array
  packages/legacy/src/queries/vms.ts
Labels: kind/bug

#283 Move the Plans "Get logs" action from the primary action area to the kebab action list
  packages/common/src/components/ActionServiceDropdown.tsx
  packages/common/src/polyfills/sdk-shim/index.ts
  packages/forklift-console-plugin/src/modules/Plans/PlanRow.tsx
  packages/forklift-console-plugin/src/modules/Plans/__tests__/__snapshots__/PlanRow.test.tsx.snap
  packages/forklift-console-plugin/src/modules/Plans/planActions.tsx
  packages/legacy/src/Plans/components/PlansTable.tsx
  packages/legacy/src/Plans/components/helpers.ts
Labels: kind/bug

#284 Add missing translations
  packages/common/src/components/Filter/FilterFromDef.tsx
  packages/common/src/components/Filter/__tests__/matchers.test.ts
  packages/common/src/components/Filter/helpers.ts
  packages/common/src/components/Filter/types.ts
  packages/common/src/components/StandardPage/__tests__/StandardPage.test.tsx
  packages/common/src/components/types.ts
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/__mocks__/console_components.tsx
  packages/forklift-console-plugin/src/components/mappings/MappingPage.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/NetworkMappingsPage.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/__tests__/MappingRow.test.tsx
  packages/forklift-console-plugin/src/modules/Plans/PlansPage.tsx
  packages/forklift-console-plugin/src/modules/Plans/__tests__/PlanRow.test.tsx
  packages/forklift-console-plugin/src/modules/Providers/ProvidersPage.tsx
  packages/forklift-console-plugin/src/modules/Providers/__tests__/ProviderRow.test.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/StorageMappingsPage.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/__tests__/MappingRow.test.tsx
Labels: kind/cleanup

#286 Add namespace to plan nav link
  packages/forklift-console-plugin/src/modules/Plans/PlanRow.tsx
  packages/legacy/src/Plans/components/PlanStatusNavLink.tsx
Labels: kind/bug

#288 Address comments form #280
  package-lock.json
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/package.json
  packages/forklift-console-plugin/src/__mocks__/console_components.tsx
  packages/forklift-console-plugin/src/modules/Providers/ProviderRow.tsx
Labels: kind/cleanup

#289 Add jsonpath to the providers list fields
  package-lock.json
  packages/common/src/components/Filter/matchers.ts
  packages/common/src/components/StandardPage/StandardPage.tsx
  packages/common/src/components/TableView/TableView.tsx
  packages/common/src/components/TableView/types.ts
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/__mocks__/console_components.tsx
  packages/forklift-console-plugin/src/__mocks__/react-i18next.tsx
  packages/forklift-console-plugin/src/components/mappings/MappingRow.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/__tests__/MappingRow.test.tsx
  packages/forklift-console-plugin/src/modules/Plans/PlanRow.tsx
  packages/forklift-console-plugin/src/modules/Plans/__tests__/PlanRow.test.tsx
  packages/forklift-console-plugin/src/modules/Providers/ProviderRow.tsx
  packages/forklift-console-plugin/src/modules/Providers/ProviderRow/HostCell.tsx
  packages/forklift-console-plugin/src/modules/Providers/ProviderRow/ProviderLink.tsx
  packages/forklift-console-plugin/src/modules/Providers/ProviderRow/StatusCell.tsx
  packages/forklift-console-plugin/src/modules/Providers/ProviderRow/TextCell.tsx
  packages/forklift-console-plugin/src/modules/Providers/ProviderRow/TextWithIcon.tsx
  packages/forklift-console-plugin/src/modules/Providers/ProviderRow/TypeCell.tsx
  packages/forklift-console-plugin/src/modules/Providers/ProviderRow/consts.tsx
  packages/forklift-console-plugin/src/modules/Providers/ProviderRow/types.ts
  packages/forklift-console-plugin/src/modules/Providers/ProvidersPage.tsx
  packages/forklift-console-plugin/src/modules/Providers/__tests__/ProviderRow.test.tsx
  packages/forklift-console-plugin/src/modules/Providers/__tests__/__snapshots__/ProviderRow.test.tsx.snap
  packages/forklift-console-plugin/src/modules/Providers/__tests__/mergeData.test.ts
  packages/forklift-console-plugin/src/modules/Providers/__tests__/mergedMockData.json
  packages/forklift-console-plugin/src/modules/Providers/data.ts
  packages/forklift-console-plugin/src/modules/Providers/providerActions.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/__tests__/MappingRow.test.tsx
Labels: kind/cleanup

#290 add missing attributes to tr, make statuscell react component
  packages/forklift-console-plugin/src/components/mappings/MappingRow.tsx
  packages/forklift-console-plugin/src/modules/Plans/PlanRow.tsx
  packages/forklift-console-plugin/src/modules/Providers/ProviderRow.tsx
  packages/forklift-console-plugin/src/modules/Providers/ProviderRow/StatusCell.tsx
Labels: kind/cleanup

#292 Factor creat ebutton out of providers page
  packages/forklift-console-plugin/src/modules/Providers/AddProviderButton.tsx
  packages/forklift-console-plugin/src/modules/Providers/EmptyStateProviders.tsx
  packages/forklift-console-plugin/src/modules/Providers/ProvidersPage.tsx
Labels: kind/cleanup

#293 Add merge data test
  packages/forklift-console-plugin/src/modules/Providers/__tests__/ProviderRow.test.tsx
  packages/forklift-console-plugin/src/modules/Providers/__tests__/data.test.getFlatData_mock_data.json
  packages/forklift-console-plugin/src/modules/Providers/__tests__/data.test.ts
Labels: kind/cleanup

#294 Test provider isManaged
  packages/forklift-console-plugin/src/modules/Providers/ProviderRow/ProviderLink.tsx
  packages/forklift-console-plugin/src/modules/Providers/__tests__/data.test.ts
  packages/forklift-console-plugin/src/modules/Providers/data.ts
  packages/forklift-console-plugin/src/modules/Providers/providerActions.tsx
Labels: kind/cleanup

#301 Add create button to empty state
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/NetworkMaps/EmptyStateNetworkMaps.tsx
  packages/forklift-console-plugin/src/modules/Plans/EmptyStatePlans.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/EmptyStateStorageMaps.tsx
Labels: kind/cleanup

#302 Remove ref cell
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/components/mappings/MappingRow.tsx
  packages/forklift-console-plugin/src/components/mappings/mappingActions.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/__tests__/__snapshots__/MappingRow.test.tsx.snap
Labels: kind/cleanup

#303 fix sorting
  packages/common/src/components/TableView/__tests__/sort.test.ts
  packages/common/src/components/TableView/sort.ts
Labels: kind/cleanup

#306 Use generated GVK from the type package
  packages/forklift-console-plugin/src/components/mappings/data.ts
  packages/forklift-console-plugin/src/modules/NetworkMaps/NetworkMappingsPage.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/dataForNetwork.ts
  packages/forklift-console-plugin/src/modules/Plans/PlansPage.tsx
  packages/forklift-console-plugin/src/modules/Plans/data.ts
  packages/forklift-console-plugin/src/modules/Providers/ProvidersPage.tsx
  packages/forklift-console-plugin/src/modules/Providers/data.ts
  packages/forklift-console-plugin/src/modules/StorageMaps/StorageMappingsPage.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/dataForStorage.ts
Labels: kind/cleanup

#309 Openstack field name update region to regionName
  packages/legacy/src/Providers/components/AddEditProviderModal/AddEditProviderModal.tsx
  packages/legacy/src/Providers/components/AddEditProviderModal/helpers.ts
  packages/legacy/src/client/helpers.ts
  packages/legacy/src/queries/mocks/secrets.mock.ts
  packages/legacy/src/queries/types/secrets.types.ts
  packages/types/src/utils/models/ProviderSecrets.ts
Labels: kind/bug

#311 Add namespace string to the empty state title
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/NetworkMaps/EmptyStateNetworkMaps.tsx
  packages/forklift-console-plugin/src/modules/Plans/EmptyStatePlans.tsx
  packages/forklift-console-plugin/src/modules/Providers/EmptyStateProviders.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/EmptyStateStorageMaps.tsx
Labels: kind/cleanup

#310 Allow using networkattachmentdefinition from different namespace
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/components/mappings/MappingPage.tsx
  packages/forklift-console-plugin/src/components/mappings/MappingRow.tsx
  packages/forklift-console-plugin/src/components/mappings/data.ts
  packages/forklift-console-plugin/src/components/mappings/mappingActions.tsx
  packages/forklift-console-plugin/src/components/mappings/styles.css
  packages/forklift-console-plugin/src/modules/NetworkMaps/NetworkMappingsPage.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/__tests__/MappingRow.test.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/__tests__/__snapshots__/MappingRow.test.tsx.snap
  packages/forklift-console-plugin/src/modules/NetworkMaps/__tests__/mergeData.test.ts
  packages/forklift-console-plugin/src/modules/NetworkMaps/__tests__/mergedNetworkData.json
  packages/forklift-console-plugin/src/modules/NetworkMaps/dataForNetwork.ts
  packages/forklift-console-plugin/src/modules/StorageMaps/StorageMappingsPage.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/__tests__/MappingRow.test.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/__tests__/__snapshots__/MappingRow.test.tsx.snap
  packages/forklift-console-plugin/src/modules/StorageMaps/__tests__/mergeData.test.ts
  packages/forklift-console-plugin/src/modules/StorageMaps/__tests__/mergedStorageData.json
  packages/forklift-console-plugin/src/modules/StorageMaps/dataForStorage.ts
  packages/forklift-console-plugin/src/utils/constants.ts
  packages/legacy/src/Plans/components/Wizard/MappingForm.tsx
Labels: kind/cleanup

#316 Refine empty states
  ci/configure/openshift.sh
  packages/common/src/components/external-link/ExternalLink.tsx
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/components/mappings/MappingPage.tsx
  packages/forklift-console-plugin/src/components/mappings/MappingRow.tsx
  packages/forklift-console-plugin/src/components/mappings/data.ts
  packages/forklift-console-plugin/src/components/mappings/mappingActions.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/EmptyStateNetworkMaps.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/NetworkMappingRow.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/NetworkMappingsWrapper.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/__tests__/mergeData.test.ts
  packages/forklift-console-plugin/src/modules/NetworkMaps/dataForNetwork.ts
  packages/forklift-console-plugin/src/modules/NetworkMaps/mappingActions.tsx
  packages/forklift-console-plugin/src/modules/Plans/EmptyStatePlans.tsx
  packages/forklift-console-plugin/src/modules/Plans/PlanRow.tsx
  packages/forklift-console-plugin/src/modules/Providers/ProviderRow.tsx
  packages/forklift-console-plugin/src/modules/Providers/ProviderRow/HostCell.tsx
  packages/forklift-console-plugin/src/modules/Providers/ProviderRow/StatusCell.tsx
  packages/forklift-console-plugin/src/modules/Providers/ProviderRow/TextCell.tsx
  packages/forklift-console-plugin/src/modules/Providers/ProviderRow/TypeCell.tsx
  packages/forklift-console-plugin/src/modules/Providers/ProviderRow/types.ts
  packages/forklift-console-plugin/src/modules/StorageMaps/EmptyStateStorageMaps.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/StorageMappingRow.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/StorageMappingsWrapper.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/__tests__/mergeData.test.ts
  packages/forklift-console-plugin/src/modules/StorageMaps/dataForStorage.ts
  packages/forklift-console-plugin/src/modules/StorageMaps/mappingActions.tsx
Labels: kind/cleanup

#319 Fix must gather url
  packages/legacy/src/queries/helpers.ts
Labels: kind/bug

#312 Port Console's LoadingBox component
  packages/common/src/components/LoadingDots.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/NetworkMappingsPage.tsx
  packages/forklift-console-plugin/src/modules/Plans/PlansPage.tsx
  packages/forklift-console-plugin/src/modules/Providers/ProvidersPage.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/StorageMappingsPage.tsx
Labels: kind/bug

#326 Add MustGather modal to the Plan list page
  ci/start-console.sh
  packages/forklift-console-plugin/src/modules/Plans/PlansPage.tsx
  packages/legacy/src/common/components/MustGatherModal.tsx
Labels: kind/bug

#329 Update README.md - vmWare -> VMware
  README.md
Labels: documentation

#331 Use stream saver instead of file saver for must gather gzip files
  package-lock.json
  packages/forklift-console-plugin/package.json
  packages/legacy/src/common/context/MustGatherContext.tsx
Labels: kind/bug

#334 Add uid to the must-gather custom name
  packages/forklift-console-plugin/src/modules/Plans/planActions.tsx
  packages/legacy/src/Plans/components/PlanActionsDropdown.tsx
  packages/legacy/src/Plans/components/PlansTable.tsx
  packages/legacy/src/Plans/components/VMMigrationDetails.tsx
  packages/legacy/src/common/components/MustGatherBtn.tsx
  packages/legacy/src/common/components/MustGatherModal.tsx
  packages/legacy/src/common/components/MustGatherWatcher.tsx
  packages/legacy/src/common/context/MustGatherContext.tsx
Labels: kind/bug

#342 Add missing tmp dir
  ci/configure/openshift.sh
Labels: kind/cleanup

#352 Configure tsconfig and eslint for cypress
  .gitignore
  cypress/.eslintrc.yml
  cypress/.prettierrc.js
  cypress/e2e/Providers.spec.cy.ts
  cypress/e2e/tests/Providers/CreateProvider.cy.ts
  cypress/support/commands.ts
  cypress/support/e2e.ts
  cypress/tsconfig.json
  package-lock.json
  package.json
  packages/forklift-console-plugin/plugin-extensions.ts
  packages/forklift-console-plugin/src/modules/Hooks/dynamic-plugin.ts
  packages/forklift-console-plugin/src/modules/Migrations/dynamic-plugin.ts
  packages/forklift-console-plugin/src/modules/NetworkMaps/dynamic-plugin.ts
  packages/forklift-console-plugin/src/modules/Plans/dynamic-plugin.ts
  packages/forklift-console-plugin/src/modules/Providers/AddProviderButton.tsx
  packages/forklift-console-plugin/src/modules/Providers/dynamic-plugin.ts
  packages/forklift-console-plugin/src/modules/StorageMaps/dynamic-plugin.ts
Labels: kind/cleanup

#353 Add npm action for e2e tests
  .github/workflows/on-pull-request.yaml
  .gitignore
  ci/build-and-push-images.sh
  ci/deploy-all.sh
  ci/deploy-cluster.sh
  ci/deploy-console-plugins.sh
  ci/deploy-console.sh
  ci/deploy-forklift-plugin.sh
  ci/install-kind.sh
  ci/install-kubectl.sh
  ci/update-types-package.sh
  ci/yaml/crds/console/console.openshift.io_consoleplugins.yaml
  ci/yaml/crds/console/console.openshift.io_consolequickstarts.yaml
  ci/yaml/crds/console/console.openshift.io_consoleyamlsamples.yaml
  ci/yaml/crds/forklift-namespace.yaml
  ci/yaml/crds/forklift/forklift.konveyor.io_forkliftcontrollers.yaml
  ci/yaml/crds/forklift/forklift.konveyor.io_hooks.yaml
  ci/yaml/crds/forklift/forklift.konveyor.io_hosts.yaml
  ci/yaml/crds/forklift/forklift.konveyor.io_migrations.yaml
  ci/yaml/crds/forklift/forklift.konveyor.io_networkmaps.yaml
  ci/yaml/crds/forklift/forklift.konveyor.io_ovirtvolumepopulators.yaml
  ci/yaml/crds/forklift/forklift.konveyor.io_plans.yaml
  ci/yaml/crds/forklift/forklift.konveyor.io_providers.yaml
  ci/yaml/crds/forklift/forklift.konveyor.io_storagemaps.yaml
  ci/yaml/forklift-console-plugin.yaml
  ci/yaml/forklift-logo.yaml
  ci/yaml/forklift-plugin.yaml.template
  ci/yaml/okd-console.yaml
  ci/yaml/openapi.yaml
  package.json
Labels: kind/cleanup

#354 Open kind port 30088
  ci/deploy-cluster.sh
Labels: kind/cleanup

#355 Add spellcheck eslint plugin
  docs/helm.md
  package-lock.json
  package.json
  packages/common/cspell.config.yaml
  packages/common/src/__mocks__/react-i18next.ts
  packages/common/src/components/Filter/EnumFilter.tsx
  packages/common/src/components/Filter/FreetextFilter.tsx
  packages/common/src/components/Filter/GroupedEnumFilter.tsx
  packages/common/src/components/Filter/SwitchFilter.tsx
  packages/common/src/components/Filter/__tests__/useUrlFilters.test.tsx
  packages/common/src/components/Filter/matchers.ts
  packages/common/src/components/Filter/types.ts
  packages/common/src/components/StandardPage/useFields.tsx
  packages/common/src/components/StandardPage/usePagination.tsx
  packages/common/src/components/TableView/ManageColumnsToolbar.tsx
  packages/common/src/components/TableView/__tests__/sort.test.ts
  packages/common/src/components/types.ts
  packages/common/src/utils/i18n.ts
  packages/config/.eslintrc.yml
  packages/forklift-console-plugin/cspell.config.yaml
  packages/forklift-console-plugin/src/__mocks__/react-i18next.tsx
  packages/forklift-console-plugin/src/modules/Migrations/dynamic-plugin.ts
  packages/forklift-console-plugin/src/modules/NetworkMaps/__tests__/MappingRow.test.tsx
  packages/forklift-console-plugin/src/modules/Plans/data.ts
  packages/forklift-console-plugin/src/modules/StorageMaps/__tests__/mergeData.test.ts
  packages/forklift-console-plugin/src/utils/constants.ts
  packages/forklift-console-plugin/src/utils/resources.ts
  packages/forklift-console-plugin/src/utils/types.ts
  packages/forklift-console-plugin/webpack.config.ts
  packages/legacy/cspell.config.yaml
  packages/legacy/src/queries/helpers.ts
  packages/types/cspell.config.yaml
  packages/types/src/utils/models/ProviderSecrets.ts
  packages/webpack/cspell.config.yaml
Labels: kind/cleanup

#356 Use openstack volumeType in plan wizard storageMap step
  packages/legacy/src/Plans/components/Wizard/helpers.tsx
  packages/legacy/src/queries/disks.ts
Labels: kind/bug

#357 Remove dev build and helm
  .github/workflows/on-pull-request.yaml
  .github/workflows/on-push.yaml
  README.md
  build/Containerfile.dev
  ci/entrypoint.dev.sh
  ci/patch-vcsim-service.sh
  ci/welcome.dev.txt
  deployment/forklift-console-plugin/.helmignore
  deployment/forklift-console-plugin/Chart.yaml
  deployment/forklift-console-plugin/templates/configmap.tpl
  deployment/forklift-console-plugin/templates/consoleplugin.tpl
  deployment/forklift-console-plugin/templates/deployment.tpl
  deployment/forklift-console-plugin/templates/service.tpl
  deployment/forklift-console-plugin/values.yaml
  docs/helm.md
  package.json
Labels: kind/cleanup

#358 Consolidate console yaml for e2e tests
  ci/deploy-console.sh
  ci/deploy-forklift-plugin.sh
  ci/yaml/forklift-console-plugin.yaml
  ci/yaml/okd-console.yaml
  package.json
Labels: kind/cleanup

#360 Test downloads sha, fix port typo
  ci/deploy-all.sh
  ci/deploy-console.sh
  ci/install-kind.sh
  ci/install-kubectl.sh
Labels: kind/cleanup

#361 Drop docker support
  .github/workflows/on-pull-request.yaml
  ci/build-and-push-images.sh
  ci/clean-cluster.sh
  ci/deploy-all.sh
  ci/deploy-cluster.sh
  ci/deploy-console.sh
  ci/start-console.sh
  ci/stop-console.sh
  package.json
Labels: kind/cleanup

#363 Add github cron job to close stale issues
  .github/workflows/cron.yaml
Labels: kind/cleanup

#364 No need to export env vars when using only podman
  .github/workflows/on-pull-request.yaml
  ci/README.md
  ci/build-and-push-images.sh
  ci/configure/openshift-auth.sh
  ci/configure/openshift.sh
  ci/deploy-all.sh
  ci/deploy-console.sh
  ci/install-kind.sh
  ci/start-console.sh
  package.json
Labels: kind/cleanup

#368 Fix local registry on fedora
  ci/deploy-cluster.sh
Labels: kind/cleanup

#371 Move config files to base dir
  .github/workflows/on-pull-request.yaml
  ci/README.forkliftci.md
  ci/clean-cluster.sh
  ci/configure/openshift.sh
  ci/deploy-all.sh
  config/cspell.wordlist.txt
  config/cypress.config.ts
  config/eslintrc.yml
  config/prettierrc.js
  config/rollup-configs.js
  config/stylelintrc.yml
  config/tsconfig.base.json
  cypress/.eslintrc.yml
  cypress/.prettierrc.js
  cypress/tsconfig.json
  package-lock.json
  package.json
  packages/common/.eslintrc.yml
  packages/common/.prettierrc.js
  packages/common/.stylelintrc.yml
  packages/common/cspell.config.yaml
  packages/common/tsconfig.json
  packages/config/.eslintignore
  packages/config/package.json
  packages/forklift-console-plugin/.eslintrc.yml
  packages/forklift-console-plugin/.prettierrc.js
  packages/forklift-console-plugin/.stylelintrc.yml
  packages/forklift-console-plugin/cspell.config.yaml
  packages/forklift-console-plugin/tsconfig.production.json
  packages/legacy/cspell.config.yaml
  packages/legacy/tsconfig.json
  packages/types/.eslintrc.yml
  packages/types/.prettierrc.js
  packages/types/.stylelintrc.yml
  packages/types/cspell.config.yaml
  packages/types/rollup.config.js
  packages/types/tsconfig.json
  packages/webpack/.eslintrc.yml
  packages/webpack/.prettierrc.js
  packages/webpack/.stylelintrc.yml
  packages/webpack/cspell.config.yaml
  packages/webpack/tsconfig.json
Labels: kind/cleanup

#373 Update docs for latest forkliftci changes
  README.md
  ci/README.forkliftci.md
  docs/building-openshift-console.md
  docs/create-service-account-with-token.md
  docs/develop-remote.md
  docs/develop-with-crc.md
  docs/develop-with-kind.md
  docs/development-server.md
  docs/setup-development-cluster-kubernetes.md
  docs/setup-development-cluster-openshift.md
  docs/using-local-registry-crc.md
  docs/using-local-registry-kind.md
Labels: documentation

#375 Add some more docs
  README.md
  docs/start-dev-server.md
Labels: documentation

#376 Tweak readme links
  README.md
Labels: documentation

#377 Rename fields labels of the Provider dialog
  packages/legacy/src/Providers/components/AddEditProviderModal/AddEditProviderModal.tsx
  packages/legacy/src/Providers/components/AddEditProviderModal/__tests__/AddEditProviderModal.test.tsx
Labels: kind/bug, backport-risk-assessed

#378 Disable openstack warm migration
  packages/legacy/src/Plans/components/Wizard/TypeForm.tsx
Labels: kind/bug
