Repository kubev2v/forklift-console-plugin, pull requests merged in 2023-02, with the labels that each got.

#165 Forward IProvider as blob to legacy dialogs
  packages/forklift-console-plugin/src/modules/Providers/__tests__/mergeData.test.ts
  packages/forklift-console-plugin/src/modules/Providers/__tests__/mergedMockData.json
  packages/forklift-console-plugin/src/modules/Providers/data.ts
  packages/forklift-console-plugin/src/modules/Providers/providerActions.tsx
Labels: kind/bug

#166 Cleanup of projects base directory
  README.md
  build/Containerfile.dev
  ci/README.md
  ci/clean-cluster.sh
  ci/configure/openshift-auth.sh
  ci/configure/openshift.sh
  ci/deploy-cluster.sh
  ci/deploy-forklift.sh
  ci/deploy-kubevirt.sh
  ci/deploy-olm.sh
  ci/entrypoint.dev.sh
  ci/start-console.sh
  ci/test-i18n.sh
  ci/welcome.dev.txt
  ci/yaml/crds/console.openshift.io_consoleplugins.yaml
  ci/yaml/crds/console.openshift.io_consolequickstarts.yaml
  ci/yaml/crds/console.openshift.io_consoleyamlsamples.yaml
  ci/yaml/crds/forklift-namespace.yaml
  ci/yaml/crds/forklift.konveyor.io_hooks.yaml
  ci/yaml/crds/forklift.konveyor.io_hosts.yaml
  ci/yaml/crds/forklift.konveyor.io_migrations.yaml
  ci/yaml/crds/forklift.konveyor.io_networkmaps.yaml
  ci/yaml/crds/forklift.konveyor.io_plans.yaml
  ci/yaml/crds/forklift.konveyor.io_providers.yaml
  ci/yaml/crds/forklift.konveyor.io_storagemaps.yaml
  ci/yaml/forklift-plugin-dev.tpl.yaml
  ci/yaml/forklift-plugin-dev.yaml
  ci/yaml/forklift-plugin.yaml
  ci/yaml/openshift-console.yaml
  docs/develop-remote.md
  docs/develop-with-crc.md
  docs/develop-with-kind.md
  docs/icons/forklift-logo-lightbg.svg
  docs/using-local-registry.md
  package.json
Labels: kind/documentation

#168 Prefix all k8s paths with OpenShift Console proxy
  packages/legacy/src/client/helpers.ts
  packages/legacy/src/queries/fetchHelpers.ts
Labels: kind/bug

#167 Update forklift CRDs to v2.4.0
  ci/yaml/crds/README.md
  ci/yaml/crds/forklift.konveyor.io_forkliftcontrollers.yaml
  ci/yaml/crds/forklift.konveyor.io_hooks.yaml
  ci/yaml/crds/forklift.konveyor.io_hosts.yaml
  ci/yaml/crds/forklift.konveyor.io_migrations.yaml
  ci/yaml/crds/forklift.konveyor.io_networkmaps.yaml
  ci/yaml/crds/forklift.konveyor.io_ovirtvolumepopulators.yaml
  ci/yaml/crds/forklift.konveyor.io_plans.yaml
  ci/yaml/crds/forklift.konveyor.io_providers.yaml
  ci/yaml/crds/forklift.konveyor.io_storagemaps.yaml
Labels: kind/documentation

#172 Close Delete provider dialog on success
  packages/common/src/components/ActionServiceDropdown.tsx
  packages/forklift-console-plugin/src/modules/Plans/planActions.tsx
  packages/forklift-console-plugin/src/modules/Providers/providerActions.tsx
Labels: kind/bug

#178 Update the i18n package path in the i18n test
  ci/test-i18n.sh
Labels: kind/bug

#187 Remove unneaded workspaces path prefix
  package-lock.json
  package.json
Labels: kind/cleanup

#196 Remove unused param
  packages/forklift-console-plugin/src/modules/Mappings/NetworkMappingRow.tsx
Labels: kind/cleanup

#190 Refine secret types
  packages/types/src/utils/models/ProviderSecrets.ts
Labels: kind/cleanup

#192 Fix vmware provider modal
  packages/legacy/src/Providers/components/AddEditProviderModal/AddEditProviderModal.tsx
  packages/legacy/src/queries/providers.ts
Labels: kind/bug

#198 Remove unneeded requirement on immutable package
  package-lock.json
  packages/common/package.json
  packages/common/src/polyfills/console-dynamic-plugin-sdk/api/internal-types.ts
Labels: kind/cleanup

#199 Change plugin metadata files to follow best practice
  packages/forklift-console-plugin/plugin-extensions.ts
  packages/forklift-console-plugin/plugin-metadata..ts
  packages/forklift-console-plugin/webpack.config.ts
Labels: kind/cleanup

#202 Polyfills eslintrc is sub-dir, should not have project field
  packages/common/src/polyfills/.eslintrc
Labels: kind/cleanup

#203 Check version before fallback to polyfill emplimentation
  package-lock.json
  packages/common/package.json
  packages/common/src/polyfills/console-dynamic-plugin-sdk/app/modal-support/useModal.ts
  packages/common/src/polyfills/sdk-shim/withModalProvider.tsx
  packages/common/src/polyfills/version/__tests__/release-version.test.ts
  packages/common/src/polyfills/version/release-version.ts
  packages/forklift-console-plugin/package.json
  packages/legacy/package.json
  packages/webpack/package.json
Labels: kind/bug

#207 Update default namespace and plugin name
  ci/start-console.sh
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/plugin-metadata..ts
  packages/forklift-console-plugin/src/modules/Mappings/NetworkMappingsPage.tsx
  packages/forklift-console-plugin/src/modules/Mappings/StorageMappingsPage.tsx
  packages/forklift-console-plugin/src/modules/Mappings/mappingActions.tsx
  packages/forklift-console-plugin/webpack.config.ts
  packages/legacy/src/Mappings/components/AddEditMappingModal.tsx
  packages/legacy/src/Plans/components/Wizard/GeneralForm.tsx
  packages/legacy/src/Plans/components/Wizard/__tests__/PlanWizard.test.tsx
  packages/legacy/src/Providers/components/AddEditProviderModal/AddEditProviderModal.tsx
  packages/legacy/src/Providers/components/AddEditProviderModal/__tests__/AddEditProviderModal.test.tsx
  packages/legacy/src/common/constants.ts
  packages/legacy/src/queries/helpers.ts
Labels: kind/feature

#208 Add debugging resources menu items
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/plugin-extensions.ts
  packages/forklift-console-plugin/src/modules/Hooks/dynamic-plugin.ts
  packages/forklift-console-plugin/src/modules/Hosts/dynamic-plugin.ts
  packages/forklift-console-plugin/src/modules/Migrations/dynamic-plugin.ts
  packages/types/src/constants/MigrationModel.v1beta1.ts
Labels: kind/feature

#220 Use warmer color palette for CRD labels
  packages/types/src/constants/HookModel.v1beta1.ts
  packages/types/src/constants/HostModel.v1beta1.ts
  packages/types/src/constants/MigrationModel.v1beta1.ts
  packages/types/src/constants/NetworkMapModel.v1beta1.ts
  packages/types/src/constants/PlanModel.v1beta1.ts
  packages/types/src/constants/ProviderModel.v1beta1.ts
  packages/types/src/constants/StorageMapModel.v1beta1.ts
Labels: kind/feature

#218 set providers default label to flex layout
  packages/forklift-console-plugin/src/modules/Providers/ProviderRow.tsx
  packages/forklift-console-plugin/src/modules/Providers/__tests__/__snapshots__/ProviderRow.test.tsx.snap
Labels: kind/feature

#217 Remove hosts menu item
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/plugin-extensions.ts
  packages/forklift-console-plugin/src/modules/Hosts/dynamic-plugin.ts
Labels: kind/feature

#238 Hide debugging menu items
  packages/forklift-console-plugin/plugin-extensions.ts
Labels: kind/bug

#237 check for valid ip before sending it to Netmask
  packages/legacy/src/Providers/components/VMwareProviderHostsTable/helpers.ts
Labels: kind/bug

#216 Check data is loaded before testing for empty data
  packages/forklift-console-plugin/src/modules/Providers/ProvidersPage.tsx
Labels: kind/bug

#244 Hide Ovirt caCert field when insecure
  packages/legacy/src/Providers/components/AddEditProviderModal/AddEditProviderModal.tsx
  packages/legacy/src/common/constants.ts
Labels: kind/bug
