Repository kubev2v/forklift-console-plugin, pull requests merged in 2023-05, with the labels that each got.

#422 Fix clean all script
  package.json
Labels: kind/cleanup

#424 fix dependencies typo
  package.json
Labels: kind/cleanup

#426 When cleaning all also clean rollup cache
  .gitignore
  packages/common/package.json
  packages/forklift-console-plugin/package.json
  packages/mocks/package.json
  packages/types/package.json
  packages/webpack/package.json
Labels: kind/cleanup

#430 Set the StorageMaps source title for OpenStack
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/EmptyStateProviders.tsx
  packages/legacy/src/Mappings/Mappings.tsx
  packages/legacy/src/common/helpers.ts
Labels: kind/bug

#431 Add generate schemas script to types package
  package-lock.json
  package.json
  packages/types/ci/generate-schemas.sh
  packages/types/package.json
  packages/types/schemas/NetworkInventory.schema.json
  packages/types/schemas/ProviderSecret.schema.json
  packages/types/schemas/ProvidersInventory.schema.json
  packages/types/schemas/StorageInventory.schema.json
  packages/types/schemas/V1beta1Hook.schema.json
  packages/types/schemas/V1beta1Host.schema.json
  packages/types/schemas/V1beta1Migration.schema.json
  packages/types/schemas/V1beta1NetworkMap.schema.json
  packages/types/schemas/V1beta1OvirtVolumePopulator.schema.json
  packages/types/schemas/V1beta1Plan.schema.json
  packages/types/schemas/V1beta1Provider.schema.json
  packages/types/schemas/V1beta1StorageMap.schema.json
Labels: kind/cleanup

#434 Init jest tests for the mock package
  packages/mocks/jest.config.ts
  packages/mocks/package.json
Labels: kind/cleanup

#435 Make getmockdata generic
  packages/mocks/src/__tests__/getMockData.test.ts
  packages/mocks/src/getMockData.ts
Labels: kind/cleanup

#436 Revert get mock data generic
  packages/mocks/src/__tests__/getMockData.test.ts
  packages/mocks/src/getMockData.ts
Labels: kind/cleanup

#437 Use data source = msw form msw mocking
  packages/forklift-console-plugin/src/mock-console-extension/dynamic-plugin.ts
Labels: kind/cleanup

#439 Add readme to the mock extension
  .eslintignore
  .gitignore
  package-lock.json
  packages/forklift-console-plugin/package.json
  packages/forklift-console-plugin/src/mock-console-extension/README.md
  packages/forklift-console-plugin/webpack.config.ts
Labels: documentation

#442 Add some more mock data
  packages/mocks/src/data/migrations.K8s.json
  packages/mocks/src/data/networkmaps.K8s.json
  packages/mocks/src/data/plans.K8s.json
  packages/mocks/src/data/providers.Inventory.json
  packages/mocks/src/data/providers.K8s.json
  packages/mocks/src/data/storagemaps.K8s.json
  packages/mocks/src/getMockData.ts
Labels: kind/cleanup

#443 Add a method to adjust namespace in mock paths
  packages/mocks/src/__tests__/getMockData.test.ts
  packages/mocks/src/data/providers.Inventory.json
  packages/mocks/src/data/providers.K8s.json
  packages/mocks/src/getMockData.ts
Labels: kind/cleanup

#444 Allow different mock sources, add har file support
  config/rollup.base.js
  config/rollup/rollup-plugin-har.js
  package-lock.json
  package.json
  packages/forklift-console-plugin/package.json
  packages/forklift-console-plugin/src/mock-console-extension/dynamic-plugin.ts
  packages/forklift-console-plugin/src/mock-console-extension/setupBrowserWorker.tsx
  packages/mocks/fileTransformer.js
  packages/mocks/jest.config.ts
  packages/mocks/package.json
  packages/mocks/src/data/recorder-brq2.har
  packages/mocks/src/getMockData.ts
  packages/mocks/src/globals.d.ts
  packages/mocks/tsconfig.json
Labels: kind/cleanup

#445 Fix typo WMS_MOCK_SOURCES to MSW_MOCK_SOURCES
  packages/forklift-console-plugin/src/mock-console-extension/dynamic-plugin.ts
  packages/mocks/src/getMockData.ts
Labels: kind/cleanup

#446 Manually bump plugin package version to 2.4.1
  packages/forklift-console-plugin/package.json
  packages/forklift-console-plugin/plugin-metadata.ts
Labels: kind/bug

#447 [release-v2.4.1] Manually bump plugin package version to 2.4.1
  packages/forklift-console-plugin/package.json
  packages/forklift-console-plugin/plugin-metadata..ts
Labels: kind/bug, backport-risk-assessed, backport 2.4

#448 Use process.env.VERSION to set the version number
  build/Containerfile
  ci/deploy-all.sh
  docs/container-images.md
  packages/forklift-console-plugin/plugin-metadata.ts
Labels: kind/bug

#454 Refactor webpack config
  package-lock.json
  packages/forklift-console-plugin/jest.config.ts
  packages/forklift-console-plugin/tsconfig.json
  packages/forklift-console-plugin/webpack.config.ts
Labels: kind/cleanup

#457 Add gitCommit and gitBranch to rollup build-metadata and banner
  config/rollup.base.js
Labels: kind/cleanup

#458 write json file is a rollup plugin
  config/rollup.base.js
  config/rollup/plugin-har.js
  config/rollup/plugin-write-json-file.js
Labels: kind/cleanup

#460 Fix UI refresh issues for providers secret data and for migration plan VMs list
  packages/legacy/src/queries/plans.ts
  packages/legacy/src/queries/providers.ts
  packages/legacy/src/queries/tree.ts
Labels: kind/bug, backport-risk-assessed, backport 2.4

#459 Update banner title
  config/rollup.base.js
Labels: kind/cleanup
