Repository kubev2v/forklift-console-plugin, pull requests merged in 2023-04, with the labels that each got.

#382 Refactor utils dir out of types package
  packages/types/src/index.ts
  packages/types/src/types/OVirtProviderSecret.ts
  packages/types/src/types/OpenShiftProviderSecret.ts
  packages/types/src/types/OpenstackProviderSecret.ts
  packages/types/src/types/ProviderSecret.ts
  packages/types/src/types/VSphereProviderSecret.ts
  packages/types/src/types/index.ts
  packages/types/src/utils/README.md
  packages/types/src/utils/index.ts
  packages/types/src/utils/modalToGroupVersionKind.ts
  packages/types/src/utils/modalToRef.ts
  packages/types/src/utils/models/ProviderSecrets.ts
  packages/types/src/utils/models/index.ts
Labels: kind/cleanup

#386 Proofread alert messages on Plan Wizard TypeForm
  packages/legacy/src/Plans/components/Wizard/TypeForm.tsx
Labels: kind/bug

#395 Fix dev server for fedora with kind
  ci/start-console.sh
  packages/forklift-console-plugin/webpack.config.ts
Labels: kind/cleanup

#396 Document the PLUGIN_URL and CONTAINER_NETWORK_TYPE env vars
  ci/README.md
Labels: documentation

#397 Add clean scripts to mock package
  packages/mocks/package.json
Labels: kind/cleanup

#398 Remove check for kind cli tool
  ci/deploy-all.sh
  ci/install-kubectl.sh
Labels: kind/cleanup

#401 Add --help option to deploy-all script
  ci/deploy-all.sh
Labels: kind/cleanup

#406 Use js for eslint config, allow use of relative paths
  config/eslintrc.js
  config/eslintrc.yml
  packages/common/.eslintrc.js
  packages/common/.eslintrc.yml
  packages/forklift-console-plugin/.eslintrc.js
  packages/forklift-console-plugin/.eslintrc.yml
  packages/mocks/.eslintrc.js
  packages/mocks/.eslintrc.yml
  packages/types/.eslintrc.js
  packages/types/.eslintrc.yml
  packages/webpack/.eslintrc.js
  packages/webpack/.eslintrc.yml
Labels: kind/cleanup

#416 Revert dropping 'Select migration network' action
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/providerActions.tsx
Labels: kind/bug

#420 Types for inventory fixes
  config/cspell.wordlist.txt
  packages/types/README.md
  packages/types/src/types/NetworkInventory.ts
  packages/types/src/types/ProviderSecret.ts
  packages/types/src/types/ProvidersInventory.ts
  packages/types/src/types/StorageInventory.ts
  packages/types/src/types/StorageTypesInventory.ts
  packages/types/src/types/host/VSphereHostInventory.ts
  packages/types/src/types/index.ts
  packages/types/src/types/k8s/IoK8sApiStorageV1StorageClass.ts
  packages/types/src/types/secret/OVirtProviderSecret.ts
  packages/types/src/types/secret/OpenShiftProviderSecret.ts
  packages/types/src/types/secret/OpenstackProviderSecret.ts
  packages/types/src/types/secret/VSphereProviderSecret.ts
  packages/types/src/types/storage/OVirtStorageDomain.ts
  packages/types/src/types/storage/OpenShiftStorageClass.ts
  packages/types/src/types/storage/OpenstackVolumeType.ts
  packages/types/src/types/storage/VSphereDataStore.ts
Labels: kind/cleanup

#411 Use Typescript project references, refactor tsconfig files
  .gitignore
  config/rollup-configs.js
  config/tsconfig.base.json
  package-lock.json
  package.json
  packages/common/package.json
  packages/common/tsconfig.json
  packages/forklift-console-plugin/package.json
  packages/forklift-console-plugin/tsconfig.json
  packages/forklift-console-plugin/tsconfig.production.json
  packages/forklift-console-plugin/webpack.config.ts
  packages/legacy/package.json
  packages/legacy/tsconfig.json
  packages/mocks/tsconfig.json
  packages/types/tsconfig.json
  packages/webpack/tsconfig.json
Labels: kind/feature

#421 Set of fixes for #411
  package-lock.json
  package.json
  packages/common/package.json
  packages/common/src/components/ActionServiceDropdown/ActionServiceDropdown.tsx
  packages/common/tsconfig.json
  packages/forklift-console-plugin/jest.config.ts
  packages/forklift-console-plugin/package.json
  packages/forklift-console-plugin/src/components/page/ManageColumnsToolbar.tsx
  packages/forklift-console-plugin/src/modules/Providers/__tests__/ProviderRow.test.tsx
  packages/forklift-console-plugin/tsconfig.json
  packages/legacy/package.json
  packages/legacy/tsconfig.json
  packages/mocks/tsconfig.json
  packages/types/package.json
  packages/types/rollup.config.js
  packages/types/tsconfig.json
  packages/webpack/tsconfig.json
Labels: kind/cleanup
