Repository kubev2v/forklift-console-plugin, pull requests merged in 2023-07, with the labels that each got.

#518 update work list
  packages/eslint-plugin/cspell.wordlist.txt
Labels: kind/cleanup

#519 Add sotry book action to main package.json file
  .gitignore
  package.json
  packages/common/package.json
Labels: kind/cleanup

#520 Use useForkliftTranslation instead of useTranslation
  packages/forklift-console-plugin/src/components/mappings/MappingRow.tsx
  packages/forklift-console-plugin/src/components/mappings/mappingActions.tsx
  packages/forklift-console-plugin/src/components/page/ManageColumnsToolbar.tsx
  packages/forklift-console-plugin/src/components/page/StandardPage.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/EmptyStateNetworkMaps.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/NetworkMappingsPage.tsx
  packages/forklift-console-plugin/src/modules/Plans/EmptyStatePlans.tsx
  packages/forklift-console-plugin/src/modules/Plans/PlanRow.tsx
  packages/forklift-console-plugin/src/modules/Plans/PlansPage.tsx
  packages/forklift-console-plugin/src/modules/Plans/planActions.tsx
  packages/forklift-console-plugin/src/modules/Providers/AddProviderButton.tsx
  packages/forklift-console-plugin/src/modules/Providers/EmptyStateProviders.tsx
  packages/forklift-console-plugin/src/modules/Providers/ProviderRow/ProviderLink.tsx
  packages/forklift-console-plugin/src/modules/Providers/ProviderRow/StatusCell.tsx
  packages/forklift-console-plugin/src/modules/Providers/ProviderRow/TypeCell.tsx
  packages/forklift-console-plugin/src/modules/Providers/ProvidersPage.tsx
  packages/forklift-console-plugin/src/modules/Providers/providerActions.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/EmptyStateStorageMaps.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/StorageMappingsPage.tsx
  packages/forklift-console-plugin/src/utils/i18n.ts
Labels: kind/cleanup

#521 Mode mock-console-extension to __mock-console-extension
  packages/forklift-console-plugin/plugin-extensions.ts
  packages/forklift-console-plugin/plugin-metadata.ts
  packages/forklift-console-plugin/src/__mock-console-extension/README.md
  packages/forklift-console-plugin/src/__mock-console-extension/dynamic-plugin.ts
  packages/forklift-console-plugin/src/__mock-console-extension/index.tsx
  packages/forklift-console-plugin/src/__mock-console-extension/logMockRequest.ts
  packages/forklift-console-plugin/src/__mock-console-extension/setupBrowserWorker.tsx
Labels: kind/cleanup

#522 Add manual constant helper SecretModel
  packages/types/README.md
  packages/types/src/types/constants/SecretModel.ts
  packages/types/src/types/constants/index.ts
  packages/types/src/types/index.ts
Labels: kind/cleanup

#524 Add CnoConfig type for the V1NetworkAttachmentDefinition spec.config
  packages/eslint-plugin/cspell.wordlist.txt
  packages/types/src/types/k8s/V1NetworkAttachmentDefinition.ts
Labels: kind/cleanup

#525 Add veth (virtual ethernet) to work list
  packages/eslint-plugin/cspell.wordlist.txt
Labels: kind/cleanup

#536 Add images to the select provider in create provider form
  packages/forklift-console-plugin/src/modules/Providers/utils/components/Galerry/SelectableCard.tsx
  packages/forklift-console-plugin/src/modules/Providers/utils/components/Galerry/SelectableGallery.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/ProvidersCreatePage.style.css
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/ProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/providerCardItems.ts
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/providerCardItems.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/images/openshift.svg
  packages/forklift-console-plugin/src/modules/Providers/views/create/images/openstack.svg
  packages/forklift-console-plugin/src/modules/Providers/views/create/images/redhat.svg
  packages/forklift-console-plugin/src/modules/Providers/views/create/images/vm.svg
Labels: kind/feature

#537 use namespace in details page breadcrumbs
  packages/forklift-console-plugin/src/modules/Providers/views/details/ProviderDetailsPage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/ProvidersListPage.tsx
Labels: kind/bug

#540 fix typos in providers details page
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OpenshiftDetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/VSphereDetailsSection.tsx
Labels: kind/bug

#545 Allow edditing vddk when settings is missing
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderVDDKImage/EditProviderVDDKImage.tsx
Labels: kind/bug

#548 Add nfs server path validation
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/__tests__/common.test.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/common.ts
Labels: kind/feature

#556 Fix type machined to machines
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/ProviderVirtualMachines.tsx
Labels: kind/bug

#554 [MTV-452] Settings page
  packages/eslint-plugin/cspell.wordlist.txt
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/plugin-extensions.ts
  packages/forklift-console-plugin/plugin-metadata.ts
  packages/forklift-console-plugin/src/modules/Overview/dynamic-plugin.ts
  packages/forklift-console-plugin/src/modules/Overview/hooks/index.ts
  packages/forklift-console-plugin/src/modules/Overview/hooks/useK8sWatchProviderNames.ts
  packages/forklift-console-plugin/src/modules/Overview/hooks/useMigrationCounts.ts
  packages/forklift-console-plugin/src/modules/Overview/hooks/useProvidersInventoryIsLive.ts
  packages/forklift-console-plugin/src/modules/Overview/images/automation.svg
  packages/forklift-console-plugin/src/modules/Overview/images/digitalTransormation.svg
  packages/forklift-console-plugin/src/modules/Overview/index.ts
  packages/forklift-console-plugin/src/modules/Overview/modal/EditCleanupMaxAgeModal.tsx
  packages/forklift-console-plugin/src/modules/Overview/modal/EditControllerCPULimitModal.tsx
  packages/forklift-console-plugin/src/modules/Overview/modal/EditControllerMemoryLimitModal.tsx
  packages/forklift-console-plugin/src/modules/Overview/modal/EditMaxVMInFlightModal.tsx
  packages/forklift-console-plugin/src/modules/Overview/modal/EditPreCopyIntervalModal.tsx
  packages/forklift-console-plugin/src/modules/Overview/modal/EditSettingsModalProps.ts
  packages/forklift-console-plugin/src/modules/Overview/modal/EditSnapshotPoolingIntervalModal.tsx
  packages/forklift-console-plugin/src/modules/Overview/modal/SettingsSelectInput.tsx
  packages/forklift-console-plugin/src/modules/Overview/modal/index.ts
  packages/forklift-console-plugin/src/modules/Overview/utils/helpers/getMigrationCounts.ts
  packages/forklift-console-plugin/src/modules/Overview/utils/helpers/getPhase.ts
  packages/forklift-console-plugin/src/modules/Overview/utils/helpers/getVmCounts.ts
  packages/forklift-console-plugin/src/modules/Overview/utils/helpers/index.ts
  packages/forklift-console-plugin/src/modules/Overview/utils/index.ts
  packages/forklift-console-plugin/src/modules/Overview/views/index.ts
  packages/forklift-console-plugin/src/modules/Overview/views/overview/OverviewPage.style.css
  packages/forklift-console-plugin/src/modules/Overview/views/overview/OverviewPage.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/components/HeaderTitle.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/components/index.ts
  packages/forklift-console-plugin/src/modules/Overview/views/overview/index.ts
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/ForkliftControllerDetailsTab.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/cards/ConditionsCard.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/cards/MigrationsCard.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/cards/OperatorCard.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/cards/SettingsCard.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/cards/WelcomeCard.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/cards/index.ts
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/index.ts
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/YAML/ForkliftControllerYAMLTab.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/YAML/index.ts
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/index.ts
  packages/forklift-console-plugin/src/modules/Plans/EmptyStatePlans.tsx
  packages/forklift-console-plugin/src/modules/Providers/dynamic-plugin.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/components/DetailsPage/DetailItem.tsx
Labels: kind/feature

#557 Don't fail on missing disks
  packages/legacy/src/Plans/components/Wizard/PlanWizard.tsx
  packages/legacy/src/Plans/components/Wizard/helpers.tsx
Labels: kind/bug

#558 [MTV-529] Add link to set default transfere network on openshift provider
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/views/details/ProviderDetailsPage.style.css
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Networks/ProviderNetworks.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/components/InventoryCellFactory.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/components/OpenshiftNetworkCell.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/components/index.ts
Labels: kind/feature

#562 Providers empty state
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/images/cloudNative.svg
  packages/forklift-console-plugin/src/modules/Providers/views/list/ProvidersListPage.style.css
  packages/forklift-console-plugin/src/modules/Providers/views/list/ProvidersListPage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/components/ProvidersEmptyState.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/components/index.ts
Labels: kind/bug

#563 Add a spinner when waiting for Save to finish
  packages/forklift-console-plugin/src/modules/Providers/modals/EditModal/EditModal.tsx
Labels: kind/bug

#564 Refactor sub components out of providers list view
  packages/forklift-console-plugin/src/modules/Overview/views/overview/OverviewPage.tsx
  packages/forklift-console-plugin/src/modules/Providers/images/modernizeMigration.svg
  packages/forklift-console-plugin/src/modules/Providers/views/list/ProvidersListPage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/components/InventoryNotReachable.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/components/ProvidersAddButton.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/components/index.ts
Labels: kind/cleanup

#565 Refactor the useMigrationCountes near to it's use
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/ForkliftControllerDetailsTab.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/cards/MigrationsCard.tsx
Labels: kind/cleanup

#566 [MTV-625] Hide provider name input until user pick type
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/ProviderCreateForm.tsx
Labels: kind/bug, QE

#567 Use labels instead of values in setting modal options dropdown
  packages/forklift-console-plugin/src/modules/Overview/modal/EditCleanupMaxAgeModal.tsx
  packages/forklift-console-plugin/src/modules/Overview/modal/EditControllerCPULimitModal.tsx
  packages/forklift-console-plugin/src/modules/Overview/modal/EditControllerMemoryLimitModal.tsx
  packages/forklift-console-plugin/src/modules/Overview/modal/EditPreCopyIntervalModal.tsx
  packages/forklift-console-plugin/src/modules/Overview/modal/EditSnapshotPoolingIntervalModal.tsx
  packages/forklift-console-plugin/src/modules/Overview/modal/SettingsSelectInput.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/cards/SettingsCard.tsx
Labels: kind/bug

#568 Use provider labels instead of raw value
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/modals/EditModal/EditModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderURL/OvirtEditURLModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OVADetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OpenshiftDetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OpenstackDetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OvirtDetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/VSphereDetailsSection.tsx
  packages/forklift-console-plugin/src/utils/enums.ts
Labels: kind/bug

#570 Capitalize the shift in openshift
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/providerCardItems.tsx
  packages/forklift-console-plugin/src/utils/enums.ts
Labels: kind/bug

#571 Add spinner to create providers edit provider forms
  packages/forklift-console-plugin/src/modules/Providers/modals/DeleteModal/DeleteModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/ProvidersCreatePage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/ProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/BaseCredentialsSection.tsx
  packages/legacy/src/Providers/components/AddEditProviderModal/AddEditProviderModal.tsx
Labels: kind/bug

#572 Operator status should favor fail or success more then running
  packages/forklift-console-plugin/src/modules/Overview/utils/helpers/getOperatorPhase.ts
  packages/forklift-console-plugin/src/modules/Overview/utils/helpers/getPhase.ts
  packages/forklift-console-plugin/src/modules/Overview/utils/helpers/index.ts
  packages/forklift-console-plugin/src/modules/Overview/views/overview/OverviewPage.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/components/OperatorStatus.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/components/index.ts
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/cards/OperatorCard.tsx
Labels: kind/bug

#573 Bump package look to prevent migtull patternfly 5 deps
  package-lock.json
  packages/forklift-console-plugin/package.json
  packages/legacy/package.json
Labels: kind/cleanup

#574 don't break on git
  packages/build/src/metadata.js
Labels: kind/cleanup

#575 Better counting of migrated vms
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Overview/utils/helpers/getMigrationCounts.ts
  packages/forklift-console-plugin/src/modules/Overview/utils/helpers/getVmCounts.ts
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/cards/MigrationsCard.tsx
Labels: kind/bug

#576 Invnetory not reachanble shoule be called as a component
  packages/forklift-console-plugin/src/modules/Overview/views/overview/OverviewPage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/ProvidersListPage.tsx
Labels: kind/cleanup

#577 Always have a network
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Networks/ProviderNetworks.tsx
Labels: kind/bug

#578 Allow empty url and token on openshift
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/secret-fields/openshiftSecretFieldValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/secret/openshiftSecretValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/views/create/ProvidersCreatePage.tsx
Labels: kind/bug

#579 Alert when inventory server is down in details page
  packages/forklift-console-plugin/src/modules/Providers/hooks/useProviderInventory.ts
  packages/forklift-console-plugin/src/modules/Providers/hooks/useProvidersInventoryList.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/ProviderDetailsPage.tsx
Labels: kind/bug

#580 Don't show no inventory error if provider is not ready
  packages/forklift-console-plugin/src/modules/Providers/views/details/ProviderDetailsPage.tsx
Labels: kind/bug

#582 Link to vmWare hosts
  packages/eslint-plugin/cspell.wordlist.txt
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/ProviderHosts.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/VSphereHostsList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/VSphereHostsRow.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/components/HostCellProps.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/components/LinkSpeedCellRenderer.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/components/MTUCellRenderer.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/components/NameCellRenderer.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/components/NetworkCellRenderer.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/components/index.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/index.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/modals/VSphereNetworkModal.style.css
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/modals/VSphereNetworkModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/modals/index.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/utils/helpers/__tests__/calculateCidrNotation.test.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/utils/helpers/calculateCidrNotation.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/utils/helpers/determineHostStatus.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/utils/helpers/index.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/utils/helpers/matchHostsToInventory.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/utils/helpers/onSaveHost.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/utils/index.ts
  packages/forklift-console-plugin/src/modules/Providers/views/list/components/InventoryCellFactory.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/components/VSphereHostCell.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/components/index.ts
  packages/types/src/types/provider/vsphere/index.ts
Labels: kind/feature

#584 Nicer vm list
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/hooks/useProviderInventory.ts
  packages/forklift-console-plugin/src/modules/Providers/hooks/useProvidersInventoryList.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/VSphereHostsRow.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/ProviderVirtualMachines.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/ProviderVirtualMachinesRow.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/components/VMCellProps.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/components/VMConcernsCellRenderer.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/components/VMNameCellRenderer.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/components/index.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/index.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/utils/helpers/getHighestPriorityConcern.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/utils/helpers/index.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/utils/index.ts
Labels: kind/feature

#585 Replace timeout with interval
  packages/forklift-console-plugin/src/modules/Providers/hooks/useProviderInventory.ts
Labels: kind/cleanup

#586 Fix typo in VDDK help
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderVDDKImage/EditProviderVDDKImage.tsx
Labels: kind/bug

#587 Use inerval in list pool to align with details pools
  packages/forklift-console-plugin/src/modules/Providers/hooks/useProvidersInventoryList.ts
Labels: kind/cleanup

#592 fix url typo
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/secret/openshiftSecretValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/views/create/ProvidersCreatePage.tsx
Labels: kind/bug

#593 Dont re render on each fetch
  packages/forklift-console-plugin/src/modules/Providers/hooks/useProviderInventory.ts
  packages/forklift-console-plugin/src/modules/Providers/hooks/useProvidersInventoryList.ts
Labels: kind/bug

#595 Make link to host smaller
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/components/NameCellRenderer.tsx
Labels: kind/bug

#596 User domain name to domain name
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/secret-fields/openstackSecretFieldValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/secret/openstackSecretValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenstackCredentialsEditFormGroups/TokenWithUsernameSecretFieldsFormGroup.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/patchSecretData.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/list/OpenstackCredentialsList.tsx
Labels: kind/bug

#597 Fix the fields shown in 'Credentials' tab in details page
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/list/OpenstackCredentialsList.tsx
Labels: kind/bug

#599 setting-value-fix
  packages/forklift-console-plugin/src/modules/Overview/modal/EditMaxVMInFlightModal.tsx
  packages/forklift-console-plugin/src/modules/Overview/modal/EditSnapshotPoolingIntervalModal.tsx
Labels: kind/bug

#600 Allow OCP temporary tokens
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/common.ts
Labels: kind/bug

#601 Don't flicker on Invalid provider error
  packages/forklift-console-plugin/src/modules/Providers/views/details/ProviderDetailsPage.tsx
Labels: kind/bug

#602 Make migration menu item inserted after virtualization menu item if exist
  packages/forklift-console-plugin/plugin-extensions.ts
Labels: kind/bug

#603 Add a helper script to create a service account for developers
  ci/create-forklift-user-account.sh
Labels: documentation

#604 OVA types
  packages/eslint-plugin/cspell.wordlist.txt
  packages/forklift-console-plugin/src/modules/Providers/hooks/useProvidersInventoryList.ts
  packages/forklift-console-plugin/src/modules/Providers/hooks/utils/constants.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/helpers/findInventoryByID.ts
  packages/types/src/models/V1beta1NetworkMapSpecMapSource.ts
  packages/types/src/types/ProviderInventory.ts
  packages/types/src/types/ProviderSecret.ts
  packages/types/src/types/ProviderVM.ts
  packages/types/src/types/ProvidersInventoryList.ts
  packages/types/src/types/provider/index.ts
  packages/types/src/types/provider/ova/Network.ts
  packages/types/src/types/provider/ova/Provider.ts
  packages/types/src/types/provider/ova/Resource.ts
  packages/types/src/types/provider/ova/TreeNode.ts
  packages/types/src/types/provider/ova/VM.ts
  packages/types/src/types/provider/ova/index.ts
  packages/types/src/types/secret/OvaProviderSecret.ts
  packages/types/src/types/secret/index.ts
Labels: kind/bug

#605 Allow to create plan with ova and openshift as source
  packages/forklift-console-plugin/src/modules/Plans/data.ts
  packages/legacy/src/Providers/components/ProvidersTable/Source/SourceProvidersTable.tsx
  packages/legacy/src/common/constants.ts
  packages/legacy/src/queries/mocks/providers.mock.ts
  packages/legacy/src/queries/tree.ts
  packages/legacy/src/queries/types/providers.types.ts
Labels: kind/feature

#606 Show different message, for error and loading
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/CredentialsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/BaseCredentialsSection.tsx
Labels: kind/bug

#608 Add openshift and ova tree fetch
  packages/legacy/src/Plans/components/Wizard/helpers.tsx
  packages/legacy/src/queries/tree.ts
Labels: kind/feature

#611 must_gather_api_cleanup_max_age setting is a string
  packages/forklift-console-plugin/src/modules/Overview/modal/EditCleanupMaxAgeModal.tsx
Labels: kind/bug

#613 OCP has ID no need to manually add it
  packages/legacy/src/Plans/components/Wizard/helpers.tsx
  packages/legacy/src/queries/tree.ts
Labels: kind/cleanup

#614 Use namespace/name notation for OCP mapping source
  packages/legacy/src/Mappings/components/MappingBuilder/helpers.ts
Labels: kind/cleanup

#616 Be less restrictive when validating CA public certs
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/common.ts
Labels: kind/bug

#617 Fix 'not available' label for source mappings and disabled mappings issues
  packages/legacy/src/Mappings/components/MappingBuilder/helpers.ts
  packages/legacy/src/Mappings/components/helpers.ts
Labels: kind/feature

#619 [MTV-567] Add plan support for OVA providers
  packages/legacy/src/Plans/components/Wizard/TypeForm.tsx
  packages/legacy/src/queries/storages.ts
Labels: kind/feature

#623 Add a comment to readme about running build
  README.md
Labels: documentation

#624 Don't flicker overview page
  packages/forklift-console-plugin/src/modules/Overview/views/overview/OverviewPage.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/index.ts
Labels: kind/cleanup

#626 FIx typeo namepace to namespace
  packages/legacy/src/Plans/components/Wizard/helpers.tsx
Labels: kind/bug

#628 Cleanup of the vms list generator method
  packages/legacy/src/Plans/components/Wizard/helpers.tsx
Labels: kind/cleanup

#633 Add CI service account for admin user and reader roles
  ci/configure/openshift.sh
  ci/create-forklift-user-account.sh
  ci/deploy-all.sh
Labels: kind/cleanup

#634 [MTV-431] Hide overview for users that can't list namespaces
  packages/forklift-console-plugin/src/modules/Overview/dynamic-plugin.ts
Labels: kind/bug

#635 CI add secrets read/edit rules to CI users
  ci/create-forklift-user-account.sh
Labels: kind/bug

#636 [MTV-431] Disable delete for reader users
  packages/forklift-console-plugin/src/components/mappings/mappingActions.tsx
  packages/forklift-console-plugin/src/modules/Plans/planActions.tsx
Labels: kind/bug

#638 Move create buttons to bottom
  packages/forklift-console-plugin/src/modules/Providers/views/create/ProvidersCreatePage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/BaseCredentialsSection.style.css
Labels: kind/bug

#639 [MTV-431] Disable create for reader only users
  packages/forklift-console-plugin/src/components/mappings/mappingActions.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/NetworkMappingsPage.tsx
  packages/forklift-console-plugin/src/modules/Plans/PlansPage.tsx
  packages/forklift-console-plugin/src/modules/Plans/planActions.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/ProvidersListPage.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/StorageMappingsPage.tsx
Labels: kind/bug

#640 [MTV-431] Disable editing in providers details views
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/BaseCredentialsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OVADetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OpenshiftDetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OpenstackDetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OvirtDetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/VSphereDetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/VSphereHostsList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Networks/ProviderNetworks.tsx
Labels: kind/bug

#644 Skip create empty secrets
  packages/forklift-console-plugin/src/modules/Providers/views/create/utils/createProvider.ts
  packages/forklift-console-plugin/src/modules/Providers/views/create/utils/createSecret.ts
  packages/forklift-console-plugin/src/modules/Providers/views/create/utils/patchSecretOwner.ts
Labels: kind/bug
