Repository kubev2v/forklift-console-plugin, pull requests merged in 2024-01, with the labels that each got.

#804 Add 'createdForResource' label back to host secrets
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/utils/helpers/onSaveHost.ts
Labels: bug

#785 Enhabce oVirt provider create, view/edit credentials help text fields
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/common.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/secret-fields/ovirtSecretFieldValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/BaseCredentialsSection.style.css
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OvirtCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/list/OvirtCredentialsList.tsx
Labels: enhancement

#813 Thanos and alert servers are now optional
  ci/configure/openshift.sh
Labels: kind/cleanup

#814 Don't cache dev webserver, a workaround bridge bug
  packages/forklift-console-plugin/webpack.config.ts
Labels: bug

#817 MTV-873: [Test] Check and update link in forklift-console-plugin
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/cards/SettingsCard.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OVADetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OpenshiftDetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OpenstackDetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OvirtDetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/VSphereDetailsSection.tsx
Labels: documentation

#818 MTV-873: [Test] Check and update link in forklift-console-plugin (backport)
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/cards/SettingsCard.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OVADetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OpenshiftDetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OpenstackDetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OvirtDetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/VSphereDetailsSection.tsx
Labels: documentation, backport 2.5

#829 :lady_beetle: Add margin under section headers
  packages/forklift-console-plugin/src/components/headers/SectionHeading.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/ProvidersCreatePage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Credentials/ProviderCredentials.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Details/ProviderDetails.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Networks/ProviderNetworks.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/ProvidersCreateVmMigrationPage.tsx
Labels: bug

#831 :lady_beetle: Set page section variant light
  packages/common/src/components-stories/TableView/TableView.stories.tsx
  packages/forklift-console-plugin/src/components/page/StandardPage.tsx
  packages/forklift-console-plugin/src/components/page/__tests__/__snapshots__/StandardPage.test.tsx.snap
  packages/forklift-console-plugin/src/modules/Overview/views/overview/OverviewPage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/ProvidersCreatePage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/ProviderPageHeadings.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Credentials/ProviderCredentials.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Details/ProviderDetails.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Networks/ProviderNetworks.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/ProvidersCreateVmMigrationPage.tsx
  packages/legacy/src/Mappings/MappingsPage.tsx
  packages/legacy/src/Plans/PlansPage.tsx
  packages/legacy/src/Plans/components/VMMigrationDetails.tsx
  packages/legacy/src/Providers/HostsPage.tsx
  packages/legacy/src/Providers/ProvidersPage.tsx
Labels: bug

#834 :feet: Add a fast Create Plan page - step 2
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/hooks/useNamespaces.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/OpenShiftVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/components/ProviderVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/EditableDescriptionItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/PlansCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/ProvidersCreateVmMigration.style.css
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/ProvidersCreateVmMigrationPage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/actions.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer.ts
Labels: enhancement

#833 :feet: Enable hiding the Welcome card within the Overview page
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Overview/dynamic-plugin.ts
  packages/forklift-console-plugin/src/modules/Overview/hooks/OverviewContextProvider.tsx
  packages/forklift-console-plugin/src/modules/Overview/utils/helpers/OverviewUserSettings.ts
  packages/forklift-console-plugin/src/modules/Overview/views/overview/OverviewPage.style.css
  packages/forklift-console-plugin/src/modules/Overview/views/overview/OverviewPage.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/components/HeaderTitle.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/components/ShowWelcomeCardButton.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/ForkliftControllerDetailsTab.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/cards/WelcomeCard.tsx
Labels: enhancement

#839 :lady_beetle: jsrsasign version is old
  package-lock.json
  packages/legacy/package.json
Labels: bug

#841 :feet: Display the "x" icon in the Overview ShowWelcomeCardButton button
  packages/forklift-console-plugin/src/modules/Overview/views/overview/components/ShowWelcomeCardButton.tsx
Labels: enhancement

#842 :lady_beetle: Make sure close icon close the label
  packages/forklift-console-plugin/src/modules/Overview/views/overview/components/ShowWelcomeCardButton.tsx
Labels: bug

#843 :lady_beetle: Remove out of line help icon
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/cards/WelcomeCard.tsx
Labels: bug

#844 :feet: Rephrase insecureSkipVerify tooltip help text
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OvirtCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/list/OvirtCredentialsList.tsx
Labels: enhancement, providers

#845 :lady_beetle: Aligh kebab with the card title
  packages/forklift-console-plugin/src/modules/Overview/views/overview/OverviewPage.style.css
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/cards/WelcomeCard.tsx
Labels: bug

#846 :soap: Refactor create actions list in overview card
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/cards/WelcomeCard.tsx
Labels: kind/cleanup

#847 :feet: Enhance OCP provider help text fields
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/modals/EditModal/EditModal.style.css
  packages/forklift-console-plugin/src/modules/Providers/modals/EditModal/EditModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditModal/types.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderURL/OpenshiftEditURLModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/ProvidersCreatePage.style.css
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/OpenshiftProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/ProviderDetailsPage.style.css
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenshiftCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/list/OpenshiftCredentialsList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OpenshiftDetailsSection.tsx
Labels: enhancement

#851 :lady_beetle: Add space between help text to input field when using Obj for TextInput.helperText
  packages/forklift-console-plugin/src/modules/Providers/modals/EditModal/EditModal.style.css
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderURL/OpenshiftEditURLModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/ProvidersCreatePage.style.css
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/OVAProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/OpenshiftProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/ProviderDetailsPage.style.css
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/list/OpenshiftCredentialsList.tsx
Labels: bug

#853 :soap: Fix OVA details - URL field help text, based on doc review
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OVADetailsSection.tsx
Labels: kind/cleanup

#854 :feet: Enhance vSphere provider help text fields
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/modals/EditModal/EditModal.style.css
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderURL/VSphereEditURLModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderVDDKImage/EditProviderVDDKImage.tsx
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/secret-fields/vsphereSecretFieldValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/views/create/ProvidersCreatePage.style.css
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/VSphereProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/ProviderDetailsPage.style.css
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/VSphereCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/list/VSphereCredentialsList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/VSphereDetailsSection.tsx
Labels: enhancement

#856 :feet: Add a edit provider credential action
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/actions/ProviderActionsDropdownItems.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/components/AlertMessageForModals.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/components/ItemIsOwnedAlert.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/components/alerts.style.css
  packages/forklift-console-plugin/src/modules/Providers/views/details/ProviderDetailsPage.style.css
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OVADetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OpenshiftDetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OpenstackDetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OvirtDetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/VSphereDetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/CreatedAtDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/CredentialsDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/NameDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/NamespaceDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/OwnerDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/ProviderDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/SecretDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/TransferNetworkDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/TypeDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/URLDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/VDDKDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/index.ts
Labels: enhancement

#855 :feet: Add a fast Create Plan page - step 3
  packages/eslint-plugin/cspell.wordlist.txt
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/hooks/useNetworks.ts
  packages/forklift-console-plugin/src/modules/Providers/hooks/useNicProfiles.ts
  packages/forklift-console-plugin/src/modules/Providers/views/create/templates/index.ts
  packages/forklift-console-plugin/src/modules/Providers/views/create/templates/networkMapTemplate.ts
  packages/forklift-console-plugin/src/modules/Providers/views/create/templates/storageMapTemplate.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/MappingList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/PlansCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/ProvidersCreateVmMigration.style.css
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/ProvidersCreateVmMigrationPage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/actions.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/getNetworksUsedBySelectedVMs.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/stateHelpers.ts
  packages/types/src/types/k8s/V1VirtualMachine.ts
Labels: enhancement

#857 :soap: Rephrase create providers title
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/views/create/ProvidersCreatePage.tsx
Labels: kind/cleanup

#858 :soap: Move secret to a section
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OpenshiftDetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OpenstackDetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OvirtDetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/VSphereDetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/index.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/SecretsSection/SecretsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/SecretsSection/components/SecretDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/SecretsSection/components/index.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/SecretsSection/index.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/index.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Details/ProviderDetails.tsx
Labels: kind/cleanup

#859 🐾 Make the VM column in providers list a link
  packages/forklift-console-plugin/src/modules/Providers/views/list/ProviderRow.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/components/VirtualMachinesCell.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/components/index.ts
Labels: enhancement

#860 :soap: Add spacer below create form
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/BaseCredentialsSection.style.css
Labels: kind/cleanup

#862 Update dependencies
  package-lock.json
  packages/forklift-console-plugin/package.json
  packages/mocks/package.json
  packages/mocks/src/data/recorder-brq2.har
  packages/mocks/src/getMockData.ts
Labels: bug

#867 🐞 [release-2.5.5] jsrsasign version is old
  package-lock.json
  packages/legacy/package.json
Labels: bug, backport 2.5.5

#868 🐞 [release-2.5.5] follow-redirects version is old
  package-lock.json
  packages/forklift-console-plugin/package.json
  packages/mocks/package.json
  packages/mocks/src/data/recorder-brq2.har
  packages/mocks/src/getMockData.ts
Labels: bug, backport 2.5.5

#869 :feet: Add sections to the provider create form
  packages/forklift-console-plugin/src/modules/Providers/views/create/ProvidersCreatePage.style.css
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/EditProvider.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/EditProviderSectionHeading.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/ProviderCreateForm.tsx
Labels: enhancement

#872 :feet: Add migration hints and actions to provider view
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/actions/ProviderActionsDropdownItems.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/ProviderDetailsPage.style.css
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Details/ProviderDetails.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/components/ProviderVirtualMachinesList.tsx
Labels: enhancement

#874 :soap: Use regular route instead of new route for the fast create form
  packages/forklift-console-plugin/src/modules/Providers/dynamic-plugin.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/components/MigrationAction.tsx
Labels: kind/cleanup

#865 :soap: Fix few text fields based on doc team review, replace reminded Trans texts to Obj
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderURL/OpenshiftEditURLModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderURL/VSphereEditURLModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderVDDKImage/EditProviderVDDKImage.tsx
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/secret-fields/ovirtSecretFieldValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/secret-fields/vsphereSecretFieldValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/OVAProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/OpenshiftProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/OpenstackProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/VSphereProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenshiftCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenstackCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenstackCredentialsEditFormGroups/ApplicationCredentialNameSecretFieldsFormGroup.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenstackCredentialsEditFormGroups/ApplicationWithCredentialsIDFormGroup.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OvirtCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/VSphereCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/list/OpenshiftCredentialsList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/list/OpenstackCredentialsList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/list/OvirtCredentialsList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/list/VSphereCredentialsList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OpenstackDetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/VSphereDetailsSection.tsx
Labels: kind/cleanup
