Repository kubev2v/forklift-console-plugin, pull requests merged in 2024-07, with the labels that each got.

#1260 :lady_beetle: Use custom create label when editint vmware boot disk
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/modals/EditRootDisk/EditRootDisk.tsx
Labels: bug

#1221 :feet: Update to PF5 - part II - onSelect, onToggle event handlers
  packages/common/src/components/ActionServiceDropdown/ActionServiceDropdown.tsx
  packages/common/src/components/Filter/AutocompleteFilter.tsx
  packages/common/src/components/Filter/EnumFilter.tsx
  packages/common/src/components/Filter/GroupedEnumFilter.tsx
  packages/common/src/components/FilterGroup/AttributeValueFilter.tsx
  packages/common/src/utils/types.ts
  packages/forklift-console-plugin/src/modules/Overview/modal/SettingsSelectInput.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/SelectProvider.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/MappingListItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/modals/VSphereNetworkModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/components/MappingListItem.tsx
Labels: enhancement

#1268 🐞 [UI] max_vm_inflight parameter is not setting
  packages/forklift-console-plugin/src/modules/Overview/modal/EditMaxVMInFlightModal.tsx
  packages/forklift-console-plugin/src/modules/Overview/modal/EditPreCopyIntervalModal.tsx
  packages/forklift-console-plugin/src/modules/Overview/modal/EditSnapshotPoolingIntervalModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditModal/utils/defaultOnConfirm.ts
Labels: bug

#1271 Add DV list to extended vm view
  package-lock.json
  packages/forklift-console-plugin/package.json
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesRowExtended.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Plan/PlanVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/types/VMData.ts
Labels: enhancement

#1272 🤖 Bump to version 2.6.4
  build/Containerfile
  packages/forklift-console-plugin/package.json
Labels: kind/ci

#1273 🤖 Release v2.6.4
  build/Containerfile
  packages/forklift-console-plugin/package.json
Labels: kind/ci

#1276 :soap: Bump version in package-lock file
  package-lock.json
Labels: kind/cleanup

#1288 :lady_beetle: Make user settings persistante
  packages/forklift-console-plugin/src/modules/NetworkMaps/views/list/NetworkMapsListPage.tsx
  packages/forklift-console-plugin/src/modules/Overview/hooks/OverviewContextProvider.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Plan/PlanVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/list/PlansListPage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/VSphereHostsList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/components/ProviderVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/ProvidersListPage.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/views/list/StorageMapsListPage.tsx
Labels: bug

#1287 :feet: Update to PF5 - part II - handle rest of event handlers
  packages/common/src/components/Filter/AutocompleteFilter.tsx
  packages/common/src/components/Filter/FreetextFilter.tsx
  packages/common/src/components/Filter/GroupedEnumFilter.tsx
  packages/common/src/components/TableView/ManageColumnsModal.tsx
  packages/forklift-console-plugin/src/components/FilterableSelect/FilterableSelect.tsx
  packages/forklift-console-plugin/src/components/page/StandardPage.tsx
  packages/forklift-console-plugin/src/modules/Overview/modal/SettingsNumberInput.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/SearchInputProvider.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/EsxiCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenshiftCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenstackCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OvirtCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/VCenterCredentialsEdit.tsx
Labels: enhancement

#1289 :feet: Allow to store table filter state in local storage
  packages/common/src/components/FilterGroup/__tests__/useUrlFilters.test.tsx
  packages/common/src/components/FilterGroup/useUrlFilters.ts
  packages/common/src/components/Page/types.ts
  packages/common/src/components/Page/useFields.tsx
  packages/common/src/components/Page/userSettings.ts
  packages/common/src/components/TableView/ManageColumnsModal.tsx
  packages/common/src/utils/types.ts
  packages/forklift-console-plugin/src/components/page/StandardPage.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/list/PlansListPage.tsx
Labels: enhancement

#1290 :soap: Store only persistent filters
  packages/common/src/components/FilterGroup/useUrlFilters.ts
  packages/common/src/components/Page/userSettings.ts
  packages/forklift-console-plugin/src/modules/Overview/utils/helpers/OverviewUserSettings.ts
Labels: kind/cleanup

#1292 🐞 Typo invalided should be invalid
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/openstack/openstackProviderValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/ova/ovaProviderValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/ovirt/ovirtProviderValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/vsphere/vsphereProviderValidator.ts
Labels: bug

#1299 :soap: Update index files in plugin code
  .gitignore
  package-lock.json
  package.json
  packages/eslint-plugin/cspell.wordlist.txt
  packages/forklift-console-plugin/package.json
  packages/forklift-console-plugin/rollup.config.js
  packages/forklift-console-plugin/src/index.ts
  packages/forklift-console-plugin/src/modules/Hooks/index.ts
  packages/forklift-console-plugin/src/modules/Migrations/index.ts
  packages/forklift-console-plugin/src/modules/NetworkMaps/index.ts
  packages/forklift-console-plugin/src/modules/NetworkMaps/views/index.ts
  packages/forklift-console-plugin/src/modules/Overview/index.ts
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/cards/WelcomeCard.tsx
  packages/forklift-console-plugin/src/modules/Plans/actions/PlanActionsDropdownItems.tsx
  packages/forklift-console-plugin/src/modules/Plans/components/PlanCriticalConditions.tsx
  packages/forklift-console-plugin/src/modules/Plans/components/PlansAddButton.tsx
  packages/forklift-console-plugin/src/modules/Plans/components/PlansEmptyState.tsx
  packages/forklift-console-plugin/src/modules/Plans/components/index.ts
  packages/forklift-console-plugin/src/modules/Plans/index.ts
  packages/forklift-console-plugin/src/modules/Plans/modals/DuplicateModal.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/ProvidersSection/ProvidersSection.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/list/PlansListPage.tsx
  packages/forklift-console-plugin/src/modules/Providers/hooks/useProvidersInventoryList.ts
  packages/forklift-console-plugin/src/modules/Providers/hooks/useTlsCertificate.ts
  packages/forklift-console-plugin/src/modules/Providers/images/index.ts
  packages/forklift-console-plugin/src/modules/Providers/index.ts
  packages/forklift-console-plugin/src/modules/Providers/modals/DeleteModal/DeleteModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditModal/EditModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditModal/utils/defaultOnConfirm.ts
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderUI/OpenshiftEditUIModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderUI/OpenstackEditUIModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderUI/OvirtEditUIModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderUI/VSphereEditUIModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderURL/OvirtEditURLModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderURL/VSphereEditURLModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderVDDKImage/EditProviderVDDKImage.tsx
  packages/forklift-console-plugin/src/modules/Providers/utils/components/DetailsPage/PageHeadings.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/ProvidersListPage.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/index.ts
  packages/forklift-console-plugin/src/modules/StorageMaps/views/index.ts
  packages/forklift-console-plugin/src/modules/index.ts
Labels: kind/cleanup
