Repository kubev2v/forklift-console-plugin, pull requests merged in 2024-06, with the labels that each got.

#1184 Bump forklift type version
  package-lock.json
  package.json
  packages/forklift-console-plugin/package.json
  packages/forklift-console-plugin/src/modules/Providers/hooks/__tests__/useProviders.test.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/providerAndSecretValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/views/create/templates/planTemplate.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/CredentialsSection.tsx
Labels: kind/cleanup

#1185 🧼 Fix Storybook errors and bump from 8.0.4 to 8.1.5
  package-lock.json
  packages/common/.eslintrc.cjs
  packages/common/.storybook/main.ts
  packages/common/.storybook/preview.tsx
  packages/common/package.json
  packages/eslint-plugin/index.js
Labels: kind/cleanup

#1186 :cleanup: Dont compile storiebook files when building the common package
  packages/common/tsconfig.json
Labels: kind/cleanup

#1188 :feet: Add hosts and folders to vSphere vms list
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/ProvidersVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/VSphereHostsList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/OVirtVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/OpenStackVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/OvaVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/ProviderVirtualMachines.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/VSphereVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/VSphereVirtualMachinesRow.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/components/VMCellProps.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/utils/filters/concernFilter.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/utils/filters/index.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/utils/hooks/index.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/utils/hooks/useInventoryVms.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/utils/hooks/useVSphereInventoryVms.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/utils/index.ts
Labels: enhancement

#1193 :feet: Add InputList component
  packages/forklift-console-plugin/src/components/InputList/InputList.style.css
  packages/forklift-console-plugin/src/components/InputList/InputList.tsx
  packages/forklift-console-plugin/src/components/InputList/index.ts
  packages/forklift-console-plugin/src/components/actions/index.ts
  packages/forklift-console-plugin/src/components/cells/index.ts
  packages/forklift-console-plugin/src/components/empty-states/index.ts
  packages/forklift-console-plugin/src/components/headers/index.ts
  packages/forklift-console-plugin/src/components/images/index.ts
  packages/forklift-console-plugin/src/components/index.ts
  packages/forklift-console-plugin/src/components/page/index.ts
  packages/forklift-console-plugin/src/components/status/index.ts
  packages/forklift-console-plugin/src/utils/fetch.ts
  packages/forklift-console-plugin/src/utils/types.ts
Labels: enhancement

#1194 :feet: Add LazyTextInput component
  packages/eslint-plugin/cspell.wordlist.txt
  packages/forklift-console-plugin/src/components/InputList/InputList.tsx
  packages/forklift-console-plugin/src/components/InputList/LazyTextInput.tsx
  packages/forklift-console-plugin/src/components/InputList/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/SettingsSection.tsx
Labels: enhancement

#1198 :soap: Use data list instead of list in inputlist
  packages/forklift-console-plugin/src/components/InputList/InputList.tsx
Labels: kind/cleanup

#1200 :lady_beetle: Warn on manual hooks in plan
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Hooks/PlanHooks.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Hooks/hooks/usePlanHooks.ts
  packages/forklift-console-plugin/src/modules/Providers/modals/components/AlertMessageForModals.tsx
Labels: bug

#1201 feet: Add disk count coloun indicating the completed disks transfered
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesRow.tsx
Labels: enhancement

#1202 :feet: Add individual disk transfer modal
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/views/details/PlanDetailsPage.style.css
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesRowExtended.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/modals/PipelineTasksModal.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/modals/index.ts
Labels: enhancement

#1203 :soap: update kubev2v types, nwe bootDisk field
  package-lock.json
  packages/forklift-console-plugin/package.json
Labels: kind/cleanup

#1197 :feet: Support LUKS keys for cold migrations from vSphere
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/SettingsSection.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/components/SetLUKSEncryptionPasswordsDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/components/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/modals/EditLUKSEncryptionPasswords/EditLUKSEncryptionPasswords.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/modals/EditLUKSEncryptionPasswords/createIndexedBase64Object.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/modals/EditLUKSEncryptionPasswords/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/modals/EditLUKSEncryptionPasswords/onLUKSEncryptionPasswordsConfirm.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/modals/index.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/components/DetailsPage/DetailItem.tsx
Labels: enhancement

#1207 :soap: Rename pipeline transfer to progress
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesRowExtended.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/modals/PipelineTasksModal.tsx
Labels: kind/cleanup

#1209 :feet: Update vddk help msgs
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/PlanCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/ProviderCardItems.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/createProviderCardItems.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditModal/EditModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderVDDKImage/EditProviderVDDKImage.tsx
  packages/forklift-console-plugin/src/modules/Providers/utils/components/Gallery/SelectableCard.tsx
  packages/forklift-console-plugin/src/modules/Providers/utils/components/Gallery/SelectableGallery.style.css
  packages/forklift-console-plugin/src/modules/Providers/utils/components/Gallery/SelectableGallery.tsx
  packages/forklift-console-plugin/src/modules/Providers/utils/components/Gallery/index.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/components/VDDKHelperText/VDDKHelperText.tsx
  packages/forklift-console-plugin/src/modules/Providers/utils/components/VDDKHelperText/index.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/components/index.ts
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/EsxiProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/ProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/VCenterProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/providerCardItems.ts
Labels: enhancement, kind/cleanup

#1210 :feet: Error when vddk init image is empty
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/modals/EditModal/EditModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderVDDKImage/EditProviderVDDKImage.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderVDDKImage/index.ts
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderVDDKImage/onEmptyVddkConfirm.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderVDDKImage/onVddkConfirm.tsx
  packages/forklift-console-plugin/src/modules/Providers/utils/components/VDDKHelperText/VDDKHelperText.tsx
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/vsphere/validateVDDKImage.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/vsphere/vsphereProviderValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/views/create/ProvidersCreatePage.style.css
  packages/forklift-console-plugin/src/modules/Providers/views/create/ProvidersCreatePage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/EsxiProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/VCenterProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/utils/createProvider.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/ProviderDetailsPage.style.css
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/VDDKDetailsItem.tsx
Labels: enhancement

#1211 :soap: Show completed pipeline tasks
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesRowExtended.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/modals/PipelineTasksModal.tsx
Labels: kind/cleanup

#1213 :lady_beetle: Don't let user edit empty vddk image without empty flag
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderVDDKImage/EditProviderVDDKImage.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderVDDKImage/index.ts
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderVDDKImage/onNoneEmptyVddkConfirm.tsx
Labels: bug

#1214 :soap: Better luks help
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/components/SetLUKSEncryptionPasswordsDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/modals/EditLUKSEncryptionPasswords/EditLUKSEncryptionPasswords.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/modals/EditLUKSEncryptionPasswords/editLUKSModalAlert.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/modals/EditLUKSEncryptionPasswords/editLUKSModalBody.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/modals/EditLUKSEncryptionPasswords/index.ts
Labels: kind/cleanup

#1218 :feet: Add FilterableSelect component
  packages/forklift-console-plugin/src/components/FilterableSelect/FilterableSelect.tsx
  packages/forklift-console-plugin/src/components/FilterableSelect/index.ts
  packages/forklift-console-plugin/src/components/index.ts
Labels: enhancement

#1220 :lady_beetle: Filter network options in vmware provider host
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/modals/VSphereNetworkModal.tsx
Labels: bug

#1222 :feet: Allow to create new namespaces
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/components/FilterableSelect/FilterableSelect.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/components/PlansCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/helpers.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/reducer.ts
Labels: enhancement

#1205 :feet: Add a plan details item to edit boot disk
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/views/details/PlanDetailsPage.style.css
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/SettingsSection.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/components/RootDiskDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/components/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/modals/EditRootDisk/EditRootDisk.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/modals/EditRootDisk/editRootDiskModalAlert.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/modals/EditRootDisk/editRootDiskModalBody.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/modals/EditRootDisk/getRootDiskLabelByKey.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/modals/EditRootDisk/index.ts
Labels: enhancement

#1208 :feet: Update to PF5 - part II - onClick event handler
  packages/forklift-console-plugin/src/modules/NetworkMaps/actions/NetworkMapActionsDropdownItems.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/componenets/NetworkMapsAddButton.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/views/details/components/MapsSection/MapsSection.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/views/details/components/ProvidersSection/ProvidersSection.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/components/ShowWelcomeCardButton.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Metrics/cards/MigrationsChartCard.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Metrics/cards/VmMigrationsChartCard.tsx
  packages/forklift-console-plugin/src/modules/Plans/actions/PlanActionsDropdownItems.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/MappingListItem.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/PlanPageHeadings.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Hooks/PlanHooks.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/components/MigrationVMsCancelButton.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/components/PlanVMsDeleteButton.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/list/components/ActionsCell.tsx
  packages/forklift-console-plugin/src/modules/Providers/actions/ProviderActionsDropdownItems.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditModal/EditModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/utils/components/CertificateUpload/CertificateUpload.tsx
  packages/forklift-console-plugin/src/modules/Providers/utils/components/CertificateUpload/FetchCertificateModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/utils/components/DetailsPage/DetailItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/ProvidersCreatePage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/EsxiProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/VCenterProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/EsxiCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenshiftCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenstackCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OvirtCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/VCenterCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/components/SelectNetworkButton.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Networks/ProviderNetworks.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/components/MigrationAction.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/components/ProvidersAddButton.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/components/MappingListItem.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/actions/StorageMapActionsDropdownItems.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/componenets/StorageMapsAddButton.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/views/details/components/MapsSection/MapsSection.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/views/details/components/ProvidersSection/ProvidersSection.tsx
Labels: enhancement

#1223 :feet: Use patternfly icons and time components
  packages/forklift-console-plugin/src/__mocks__/console_components.tsx
  packages/forklift-console-plugin/src/components/ConsoleTimestamp/ConsoleTimestamp.style.css
  packages/forklift-console-plugin/src/components/ConsoleTimestamp/ConsoleTimestamp.tsx
  packages/forklift-console-plugin/src/components/ConsoleTimestamp/index.ts
  packages/forklift-console-plugin/src/components/cells/StatusCell.tsx
  packages/forklift-console-plugin/src/components/cells/utils.tsx
  packages/forklift-console-plugin/src/components/index.ts
  packages/forklift-console-plugin/src/components/status/StatusIcon.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/views/details/components/ConditionsSection/ConditionsSection.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/views/details/components/DetailsSection/components/CreatedAtDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/views/list/components/StatusCell.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/components/OperatorStatus.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/components/PodsTable.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/cards/OperatorCard.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/ConditionsSection/ConditionsSection.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/DetailsSection/components/CreatedAtDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/MigrationsSection/components/MigrationsTable.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/components/RootDiskDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesRow.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesRowExtended.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/components/ConditionsCellRenderer.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/modals/PipelineTasksModal.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/list/PlanRow.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/list/components/PlanStatusIcon.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/ConditionsSection/ConditionsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/CreatedAtDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/VDDKDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/components/NetworkCellRenderer.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/utils/helpers/getCategoryTitle.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/components/StatusCell.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/views/details/components/ConditionsSection/ConditionsSection.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/views/details/components/DetailsSection/components/CreatedAtDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/views/list/components/StatusCell.tsx
Labels: enhancement

#1227 :feet: Remove unused settings must gather cleanup
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Overview/modal/EditCleanupMaxAgeModal.tsx
  packages/forklift-console-plugin/src/modules/Overview/modal/index.ts
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/cards/SettingsCard.tsx
Labels: enhancement

#1229 :lady_beetle: fix timestamp format
  packages/forklift-console-plugin/src/components/ConsoleTimestamp/ConsoleTimestamp.tsx
Labels: bug

#1231 :lady_beetle: Add hash to package-lock.json file'
  package-lock.json
Labels: bug

#1234 :lady_beetle: Allow to add and filter namespace when editing a plan
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/modals/EditPlanTargetNamespace/EditPlanTargetNamespace.tsx
Labels: bug

#1238 :lady_beetle: Dont spellcheck none spellable texts
  packages/common/src/components-stories/FormGroupWithHelpText.stories.tsx
  packages/forklift-console-plugin/src/components/FilterableSelect/FilterableSelect.tsx
  packages/forklift-console-plugin/src/components/InputList/LazyTextInput.tsx
  packages/forklift-console-plugin/src/modules/Plans/modals/DuplicateModal.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Hooks/PlanHooks.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditModal/EditModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderVDDKImage/EditProviderVDDKImage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/EsxiProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/OVAProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/OpenshiftProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/OpenstackProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/OvirtProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/ProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/VCenterProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/FieldWithClipboardCopy.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/MaskedField.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/EsxiCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenshiftCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenstackCredentialsEditFormGroups/ApplicationCredentialNameSecretFieldsFormGroup.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenstackCredentialsEditFormGroups/ApplicationWithCredentialsIDFormGroup.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenstackCredentialsEditFormGroups/PasswordSecretFieldsFormGroup.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenstackCredentialsEditFormGroups/TokenWithUserIDSecretFieldsFormGroup.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenstackCredentialsEditFormGroups/TokenWithUsernameSecretFieldsFormGroup.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OvirtCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/VCenterCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/modals/VSphereNetworkModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/components/PlansCreateForm.tsx
Labels: bug

#1241 🐞 Dont focus on input texts when edit modal open
  packages/forklift-console-plugin/src/modules/Providers/modals/EditModal/EditModal.tsx
Labels: bug

#1242 :feet: Add status column to jobs and pvcs tables
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesRowExtended.tsx
Labels: enhancement

#1245 :feet: Add an unselect hint to selected gallary card
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/PlanCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/ProviderCreateForm.tsx
Labels: enhancement

#1248 🐾 Update documentation links
  packages/forklift-console-plugin/src/modules/NetworkMaps/componenets/NetworkMapsEmptyState.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/cards/SettingsCard.tsx
  packages/forklift-console-plugin/src/modules/Plans/componenets/PlansEmptyState.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/modals/EditLUKSEncryptionPasswords/editLUKSModalBody.tsx
  packages/forklift-console-plugin/src/modules/Providers/utils/components/VDDKHelperText/VDDKHelperText.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/TransferNetworkDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/TypeDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/URLDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/VDDKDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/components/ProvidersEmptyState.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/componenets/StorageMapsEmptyState.tsx
Labels: enhancement

#1250 :lady_beetle: Add true and false staus icons
  packages/forklift-console-plugin/src/components/status/StatusIcon.tsx
Labels: bug

#1252 :lady_beetle: Make host default network label gray
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/components/NetworkCellRenderer.tsx
Labels: bug

#1256 :lady_beetle: Set initial plan target namespace
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/createInitialState.ts
Labels: bug
