Repository kubev2v/forklift-console-plugin, pull requests merged in 2024-02, with the labels that each got.

#877 :feet: t: Add a fast Create Plan page - step 5
  packages/forklift-console-plugin/src/modules/Providers/hooks/useDisks.ts
  packages/forklift-console-plugin/src/modules/Providers/hooks/useStorages.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/PlansCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/actions.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/getStoragesUsedBySelectedVMs.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/mapSourceToLabels.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/stateHelpers.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/useFetchEffects.ts
  packages/types/src/types/provider/openstack/Volume.ts
  packages/types/src/types/provider/openstack/index.ts
  packages/types/src/types/provider/openstack/model.ts
Labels: enhancement

#879 :lady_beetle: VM list how to create info should be blue
  packages/eslint-plugin/cspell.wordlist.txt
  packages/forklift-console-plugin/src/modules/Providers/views/details/OVirtProviderDetailsPage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/OpenStackProviderDetailsPage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/OpenshiftProviderDetailsPage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/OvaProviderDetailsPage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/VSphereProviderDetailsPage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Details/ProviderDetails.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/OVirtVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/OpenShiftVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/OpenStackVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/OvaVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/ProviderVirtualMachines.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/VSphereVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/components/ProviderVirtualMachinesList.tsx
Labels: bug, providers

#881 :soap: ocp resources use ids
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/components/ProviderVirtualMachinesList.tsx
  packages/types/src/types/provider/openshift/Resource.ts
Labels: kind/cleanup

#884 :soap: Create a Wrapper StandardPageWithSelection
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/components/page/StandardPageWithSelection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/VSphereHostsList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/components/SelectNetworkButton.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/components/index.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/OVirtVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/OpenShiftVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/OpenStackVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/OvaVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/ProviderVirtualMachines.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/VSphereVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/components/ProviderVirtualMachinesList.tsx
Labels: kind/cleanup

#885 :soap: Rename the migrate button create migration plan
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/components/MigrationAction.tsx
Labels: kind/cleanup, providers

#886 :feet: Add a placeholder create plan, to replace the wizard
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/components/images/logos.tsx
  packages/forklift-console-plugin/src/components/images/resources/openshift.svg
  packages/forklift-console-plugin/src/components/images/resources/openstack.svg
  packages/forklift-console-plugin/src/components/images/resources/ova.svg
  packages/forklift-console-plugin/src/components/images/resources/redhat.svg
  packages/forklift-console-plugin/src/components/images/resources/vm.svg
  packages/forklift-console-plugin/src/modules/Plans/dynamic-plugin.ts
  packages/forklift-console-plugin/src/modules/Plans/views/create/PlanCreatePage.style.css
  packages/forklift-console-plugin/src/modules/Plans/views/create/PlanCreatePage.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/ChipsToolbarProviders.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/FiltersToolbarProviders.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/PlanCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/ProviderCardContent.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/ProviderCardItems.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/ProvidersVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/SearchInputProvider.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/SelectProvider.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/createProviderCardItems.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/providerCardTitle.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/constanats/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/create/constanats/providerTypes.ts
  packages/forklift-console-plugin/src/modules/Plans/views/create/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/create/states/PlanCreatePageStore.ts
  packages/forklift-console-plugin/src/modules/Plans/views/create/states/index.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/components/Galerry/SelectableCard.tsx
  packages/forklift-console-plugin/src/modules/Providers/utils/components/Galerry/SelectableGallery.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/providerCardItems.ts
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/providerCardItems.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/images/openstack.svg
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/BaseCredentialsSection.style.css
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/ProviderVirtualMachines.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/ProvidersCreateVmMigrationPage.tsx
Labels: enhancement

#887 :soap: Bump node version
  .github/workflows/on-pull-request.yaml
  build/Containerfile
  packages/mocks/src/definitions/basic/namespaces.mock.ts
  packages/mocks/src/definitions/basic/networks.mock.ts
  packages/mocks/src/definitions/basic/providers.mock.ts
  packages/mocks/src/definitions/basic/storages.mock.ts
  packages/mocks/src/definitions/basic/vms.mock.ts
Labels: kind/cleanup

#888 :soap: Add jdoc to StandardPageWithSelection
  packages/forklift-console-plugin/src/components/page/StandardPage.tsx
  packages/forklift-console-plugin/src/components/page/StandardPageWithSelection.tsx
Labels: kind/cleanup

#890 :soap: Add more class to create plan
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/components/page/StandardPage.tsx
  packages/forklift-console-plugin/src/components/page/__tests__/__snapshots__/StandardPage.test.tsx.snap
  packages/forklift-console-plugin/src/modules/Plans/views/create/PlanCreatePage.style.css
  packages/forklift-console-plugin/src/modules/Plans/views/create/PlanCreatePage.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/ProvidersVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/OVirtVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/OpenShiftVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/OpenStackVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/OvaVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/ProviderVirtualMachines.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/VSphereVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/components/ProviderVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/ProvidersCreateVmMigration.style.css
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/ProvidersCreateVmMigrationPage.tsx
Labels: kind/cleanup

#892 :feet: Update provider types
  packages/eslint-plugin/cspell.wordlist.txt
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/vsphereProviderValidator.ts
  packages/types/src/models/V1beta1PlanSpec.ts
  packages/types/src/types/secret/OVirtProviderSecret.ts
  packages/types/src/types/secret/OpenShiftProviderSecret.ts
  packages/types/src/types/secret/OpenstackProviderSecret.ts
  packages/types/src/types/secret/VSphereProviderSecret.ts
Labels: enhancement

#893 :feet: Add cacert to ocp
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/secret-fields/openshiftSecretFieldValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/views/create/utils/createSecret.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenshiftCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/list/OpenshiftCredentialsList.tsx
Labels: enhancement, providers

#894 :feet: Add cacert to vsphere
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/secret-fields/vsphereSecretFieldValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/VSphereCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/list/VSphereCredentialsList.tsx
Labels: enhancement, providers

#896 :lady_beetle: Save host secret first
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/utils/helpers/onSaveHost.ts
Labels: bug, providers

#902 :soap: Move helper methods to create host to helper files
  packages/forklift-console-plugin/src/modules/Providers/views/create/ProvidersCreatePage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/utils/createProviderSecret.ts
  packages/forklift-console-plugin/src/modules/Providers/views/create/utils/index.ts
  packages/forklift-console-plugin/src/modules/Providers/views/create/utils/patchProviderSecretOwner.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/utils/helpers/createHost.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/utils/helpers/createHostSecret.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/utils/helpers/index.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/utils/helpers/onSaveHost.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/utils/helpers/patchHostSecretOwner.ts
Labels: kind/cleanup

#900 :robot: Allow partial deploy
  ci/deploy-all.sh
  ci/deploy-forklift.sh
Labels: kind/ci

#901 :soap: Refactor localized forklift trans
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/NetworkMaps/EmptyStateNetworkMaps.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/cards/WelcomeCard.tsx
  packages/forklift-console-plugin/src/modules/Plans/EmptyStatePlans.tsx
  packages/forklift-console-plugin/src/modules/Plans/planActions.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/PlanCreatePage.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/DeleteModal/DeleteModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderURL/OpenshiftEditURLModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderURL/OpenstackEditURLModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderURL/VSphereEditURLModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderVDDKImage/EditProviderVDDKImage.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/components/ItemIsOwnedAlert.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/ProvidersCreatePage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/OVAProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/OpenshiftProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/OpenstackProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/VSphereProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenshiftCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenstackCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OvirtCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/VSphereCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/list/OpenshiftCredentialsList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/list/OpenstackCredentialsList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/list/OvirtCredentialsList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/list/VSphereCredentialsList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OpenstackDetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/VSphereDetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/VDDKDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Details/ProviderDetails.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/ProviderVirtualMachines.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/ProvidersListPage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/components/ProvidersEmptyState.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/ProvidersCreateVmMigrationPage.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/EmptyStateStorageMaps.tsx
  packages/forklift-console-plugin/src/utils/i18n.ts
  packages/forklift-console-plugin/src/utils/i18n.tsx
Labels: kind/cleanup

#905 :soap: Migrate action string changes
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/actions/ProviderActionsDropdownItems.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/components/MigrationAction.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/ProvidersCreateVmMigrationPage.tsx
Labels: kind/cleanup

#906 :lady_beetle: Fix helper text values in ovirt username input
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OvirtCredentialsEdit.tsx
Labels: bug

#907 :feet: Add a create plan progress
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/views/create/PlanCreatePage.style.css
  packages/forklift-console-plugin/src/modules/Plans/views/create/PlanCreatePage.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/PlanCreateProgress.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/index.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/ProviderVirtualMachines.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/ProvidersCreateVmMigrationPage.tsx
Labels: enhancement

#908 :lady_beetle: Fix validation of URL and VDDK
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/vsphere/validateVDDKImage.ts
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/OVAProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/utils/createProviderSecret.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/patchSecretData.ts
Labels: bug

#909 :feet: Allow ESXi endpoint
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/vsphere/validateVCenterURL.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/vsphere/vsphereSecretFieldValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/VSphereProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/VSphereCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/TypeDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/modals/VSphereNetworkModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/utils/helpers/onSaveHost.ts
Labels: enhancement

#899 :feet: Add a fast Create Plan page - step 7
  packages/eslint-plugin/cspell.wordlist.txt
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/ProvidersCreateVmMigrationPage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/components/EditableDescriptionItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/components/PlansCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/components/StateAlerts.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/actions.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/calculateMappings.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/createInitialState.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/getNetworksUsedBySelectedVMs.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/hasMultipleNicsOnTheSameNetwork.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/hasMultiplePodNetworkMappings.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/hasNicWithEmptyProfile.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/helpers.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/reducer.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/types.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/useFetchEffects.ts
Labels: enhancement

#912 :feet: Plan details page scaffolding
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/dynamic-plugin.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/PlanDetailsPage.style.css
  packages/forklift-console-plugin/src/modules/Plans/views/details/PlanDetailsPage.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/Loading.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/Suspend.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Details/PlanDetails.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Details/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Hooks/PlanHooks.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Hooks/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Mappings/PlanMappings.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Mappings/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/PlanVirtualMachines.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/YAML/PlanYAML.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/YAML/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/index.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/components/DetailsPage/PageHeadings.tsx
Labels: enhancement

#913 :feet: Create a new Metrics tab - part 6
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Metrics/ForkliftControllerMetricsTab.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Metrics/cards/ChartsCard.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Metrics/cards/MigrationsChartCard.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Metrics/cards/VmMigrationsChartCard.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Metrics/cards/index.ts
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Metrics/utils/timeRangeOptions.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Metrics/utils/toDataPointsHelper.tsx
Labels: enhancement

#916 :soap: Refactor plan details suspend
  packages/forklift-console-plugin/src/modules/Plans/views/details/PlanDetailsPage.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Details/PlanDetails.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Hooks/PlanHooks.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Mappings/PlanMappings.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/PlanVirtualMachines.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/YAML/PlanYAML.tsx
Labels: kind/cleanup, plans

#917 :soap: Move hooks tab to the end of the tabs list in plans details page
  packages/forklift-console-plugin/src/modules/Plans/views/details/PlanDetailsPage.tsx
Labels: kind/cleanup, plans

#919 :robot: Update package lock
  package-lock.json
Labels: kind/ci

#920 :robot: Better ci printout
  ci/deploy-all-providers.sh
  ci/deploy-openstack-provider.sh
  ci/deploy-ovirt-provider.sh
  ci/deploy-vmware-provider.sh
Labels: kind/ci

#921 :lady_beetle: Replace mapping should return an object
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/changeMapping.ts
Labels: bug

#922 :feet: Implement selected source provider in new plan
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/PlanCreateForm.tsx
Labels: enhancement, plans

#923 :soap: Add sub section headers to fast create plan form
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/PlanCreateProgress.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/ProvidersCreateVmMigration.style.css
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/ProvidersCreateVmMigrationPage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/components/PlansCreateForm.tsx
Labels: kind/cleanup, plans

#925 :lady_beetle: Use validationState instead of validationMsg
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/OpenshiftProviderCreateForm.tsx
Labels: bug

#926 :lady_beetle: Fix provider-and-secret validtion
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/openshift/openshiftSecretValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/openshift/validateOpenshiftURL.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/openstack/openstackSecretValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/ovirt/ovirtSecretValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/providerAndSecretValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/vsphere/vsphereSecretValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/OpenshiftProviderCreateForm.tsx
Labels: bug, providers

#927 :soap: Allow pressing on the select source step to go back
  packages/forklift-console-plugin/src/modules/Plans/views/create/PlanCreatePage.style.css
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/PlanCreateProgress.tsx
Labels: kind/cleanup, plans

#928 Clean selected source when applying new filter
  packages/forklift-console-plugin/src/modules/Plans/views/create/states/PlanCreatePageStore.ts
Labels: kind/cleanup, plans

#929 :soap: Show only ready providers for source of migration
  packages/forklift-console-plugin/src/modules/Plans/views/create/PlanCreatePage.tsx
Labels: kind/cleanup, plans

#930 :soap: Get initial state of new plan form from state
  packages/forklift-console-plugin/src/modules/Plans/views/create/PlanCreatePage.tsx
Labels: kind/cleanup, plans

#924 :feet: Fetch and verify certificate from tls-certificate endpoint
  package-lock.json
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/package.json
  packages/forklift-console-plugin/src/modules/Providers/hooks/__tests__/useTlsCertifcate.test.ts
  packages/forklift-console-plugin/src/modules/Providers/hooks/index.ts
  packages/forklift-console-plugin/src/modules/Providers/hooks/useTlsCertificate.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/components/CertificateUpload/CertificateUpload.style.css
  packages/forklift-console-plugin/src/modules/Providers/utils/components/CertificateUpload/CertificateUpload.tsx
  packages/forklift-console-plugin/src/modules/Providers/utils/components/CertificateUpload/FetchCertificateModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/utils/components/CertificateUpload/VerifyCertificate.tsx
  packages/forklift-console-plugin/src/modules/Providers/utils/components/CertificateUpload/index.ts
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/EditProvider.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/VSphereCredentialsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/VSphereCredentialsEdit.tsx
Labels: enhancement

#931 :lady_beetle: openshift-validator-should-not-return-null
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/vsphere/vsphereProviderValidator.ts
Labels: bug, providers

#932 :feet: Add pods tab to overview page
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/components/status/StatusIcon.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/OverviewPage.style.css
  packages/forklift-console-plugin/src/modules/Overview/views/overview/OverviewPage.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/components/PodsTable.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/components/index.ts
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/ForkliftControllerDetailsTab.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/cards/ControllerCard.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/cards/index.ts
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Pods/ForkliftControllerPodsTab.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Pods/cards/PodsCard.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Pods/cards/index.ts
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Pods/index.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/ConditionsSection/ConditionsSection.tsx
Labels: enhancement

#934 :robot: Add sudo to the ci script example
  ci/deploy-all.sh
Labels: kind/ci

#939 :feet: Show pods on overview tab instead of pods tab
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Overview/views/overview/OverviewPage.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/cards/ControllerCard.tsx
Labels: enhancement

#940 :lady_beetle: Add yaml example for network map
  packages/forklift-console-plugin/src/modules/NetworkMaps/dynamic-plugin.ts
  packages/forklift-console-plugin/src/modules/NetworkMaps/yamlTemplates/defaultYamlTemplate.ts
  packages/forklift-console-plugin/src/modules/NetworkMaps/yamlTemplates/index.ts
Labels: bug

#946 :bug: Remove extra primary button in create plan page
  packages/forklift-console-plugin/src/modules/Plans/views/create/PlanCreatePage.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/ProvidersVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/OVirtVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/OpenShiftVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/OpenStackVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/OvaVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/ProviderVirtualMachines.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/VSphereVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/components/ProviderVirtualMachinesList.tsx
Labels: bug

#947 :soap: Hide unimplemented plan tabs
  packages/forklift-console-plugin/src/modules/Plans/views/details/PlanDetailsPage.tsx
Labels: kind/cleanup

#950 :feet: Add a migrations section to plans details tab
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Overview/views/overview/components/PodsTable.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/PlanDetailsPage.style.css
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/MigrationsSection/MigrationsSection.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/MigrationsSection/components/MigrationsTable.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/MigrationsSection/components/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/MigrationsSection/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Details/PlanDetails.tsx
Labels: enhancement

#951 :feet: Nicer migration vm column
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/MigrationsSection/components/MigrationsTable.tsx
Labels: enhancement

#952 :soap: Cleanup unused mapping pages
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/components/mappings/MappingPage.tsx
  packages/forklift-console-plugin/src/components/mappings/MappingRow.tsx
  packages/forklift-console-plugin/src/components/mappings/data.ts
  packages/forklift-console-plugin/src/components/mappings/mappingActions.tsx
  packages/forklift-console-plugin/src/components/mappings/styles.css
Labels: kind/cleanup

#954 :lady_beetle: Don't fail when certificate is not valid
  packages/forklift-console-plugin/src/modules/Providers/hooks/useTlsCertificate.ts
Labels: bug
