Repository kubev2v/forklift-console-plugin, pull requests merged in 2024-05, with the labels that each got.

#1136 :lady_beetle: Allow to choose NADs from default namespace
  packages/forklift-console-plugin/src/modules/Plans/views/details/utils/mapMappingsIdsToLabels.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/calculateMappings.ts
Labels: bug

#1137 bump kubev2v types for preserveStaticIPs
  package-lock.json
  packages/forklift-console-plugin/package.json
Labels: kind/cleanup

#1139 :soap: ephrase the text label for the preserveStaticIPs flag
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/components/PreserveStaticIPsDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/modals/EditPlanPreserveStaticIPs/EditPlanPreserveStaticIPs.tsx
Labels: kind/cleanup

#1141 Release v2.6.2
  build/Containerfile
  packages/forklift-console-plugin/package.json
Labels: kind/cleanup

#1142 :soap: bump to version 2.5.7
  .github/workflows/on-pull-request.yaml
  build/Containerfile
  packages/forklift-console-plugin/package.json
Labels: kind/cleanup

#1148 :robot: Use bearer auth for remote ocp
  ci/configure/openshift.sh
  package-lock.json
Labels: kind/ci

#1149 🐞 Migration Plan (UI) - select VM from the list takes ~3-5sec
  packages/forklift-console-plugin/src/components/page/StandardPage.tsx
  packages/forklift-console-plugin/src/components/page/StandardPageWithSelection.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/ProvidersVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/steps/SelectSourceProvider/MemoizedProviderVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/steps/SelectSourceProvider/SelectSourceProvider.tsx
  packages/forklift-console-plugin/src/modules/Providers/utils/types/ProviderData.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/ProviderVirtualMachines.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/components/ProviderVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/utils/useInventoryVms.tsx
Labels: bug

#1151 🐞 pagination is slow on pages with items > 10K
  packages/forklift-console-plugin/src/components/page/StandardPage.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/views/list/NetworkMapsListPage.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Plan/PlanVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/list/PlansListPage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/VSphereHostsList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/components/ProviderVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/ProvidersListPage.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/views/list/StorageMapsListPage.tsx
Labels: bug

#1153 :lady_beetle: Dont sort on filter change
  packages/forklift-console-plugin/src/components/page/StandardPage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/utils/useInventoryVms.tsx
Labels: bug

#1154 :soap: Move web ui link to a new details item
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OVADetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OpenshiftDetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OpenstackDetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OvirtDetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/VSphereDetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/ExternalManagementLinkDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/NamDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/NameAndUiLinkDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/index.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/index.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/utils/getOvirtProviderWebUILink.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/utils/getProviderUIAnnotation.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/utils/index.ts
Labels: kind/cleanup

#1155 :feet: Add link to vmware ui
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderUI/EditProviderUIModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderUI/OvirtEditUIModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/VSphereDetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/utils/getOvirtProviderWebUILink.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/utils/getVSphereProviderWebUILink.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/utils/index.ts
Labels: enhancement

#1156 :robot: CI sould look for forklift routes if exist
  ci/start-console.sh
Labels: kind/ci

#1158 :feet: Provide the OpenStack UI URL as part of the OpenStack provider detais page
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderUI/EditProviderUIModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderUI/OpenstackEditUIModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderUI/index.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/openstack/index.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/openstack/validateOpenstackUILink.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/openstack/validateOpenstackURL.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OpenstackDetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/utils/getOpenstackProviderWebUILink.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/utils/index.ts
Labels: enhancement

#1160 🐞 look and position of plan action button in plan details
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/views/details/PlanDetailsPage.style.css
  packages/forklift-console-plugin/src/modules/Plans/views/details/PlanDetailsPage.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/DetailsSection/DetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/PlanPageHeadings.tsx
  packages/forklift-console-plugin/src/modules/Providers/utils/components/DetailsPage/PageHeadings.tsx
Labels: bug

#1159 :feet: Provide the OCP UI URL as part of the remote OCP provider detais page
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderUI/EditProviderUIModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderUI/OpenshiftEditUIModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderUI/index.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/openshift/index.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/openshift/validateOpenshiftUILink.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OpenshiftDetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/utils/getOpenshiftProviderWebUILink.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/utils/index.ts
Labels: enhancement

#1162 :soap: remove un used wrapper
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/DetailsSection/DetailsSection.tsx
Labels: kind/cleanup

#1161 :robot: add https:// before the route we get automatically
  ci/start-console.sh
Labels: kind/ci

#1163 🐞 plans details vms, use same icons in expanded view
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesRow.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesRowExtended.tsx
Labels: bug

#1165 🐞 Plans -> details tab -> settings section, no title when data is missing
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/SettingsSection.tsx
Labels: bug

#1168 🐞 plan -> mapping -> error on no networks
  packages/forklift-console-plugin/src/modules/Plans/views/details/PlanDetailsPage.style.css
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Mappings/PlanMappings.tsx
Labels: bug

#1169 Add pvc information for a vm in extended view
  packages/eslint-plugin/cspell.wordlist.txt
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesRowExtended.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Plan/PlanVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/types/VMData.ts
Labels: enhancement

#1170 🐾 Plan -> vm list don't show plan status conditions
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Plan/PlanVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Plan/PlanVirtualMachinesRow.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/components/ConditionsCellRenderer.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/components/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/types/VMData.ts
Labels: enhancement

#1172 :lady_beetle: Save network map target namespace
  packages/forklift-console-plugin/src/modules/NetworkMaps/views/details/components/MapsSection/MapsSection.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/views/details/components/ProvidersSection/ProvidersSection.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/utils/mapMappingsIdsToLabels.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/utils/patchPlanMappingsData.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/calculateMappings.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/useSaveEffect.ts
  packages/forklift-console-plugin/src/modules/StorageMaps/views/details/components/MapsSection/MapsSection.tsx
Labels: bug

#1173 :lady_beetle: Save network map target namespace
  packages/forklift-console-plugin/src/modules/NetworkMaps/views/details/components/MapsSection/MapsSection.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/views/details/components/ProvidersSection/ProvidersSection.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/utils/mapMappingsIdsToLabels.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/utils/patchPlanMappingsData.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/calculateMappings.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/useSaveEffect.ts
  packages/forklift-console-plugin/src/modules/StorageMaps/views/details/components/MapsSection/MapsSection.tsx
Labels: bug

#1174 :lady_beetle: Hide PreserveStaticIPsDetailsItem in 2.6.
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/SettingsSection.tsx
Labels: bug

#1175 :lady_beetle: Check for empty name when extracting namespace
  packages/forklift-console-plugin/src/modules/Plans/views/details/utils/patchPlanMappingsData.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/useSaveEffect.ts
Labels: bug

#1176 :lady_beetle: Check for empty name when extracting namespace [2.6.2]
  packages/forklift-console-plugin/src/modules/Plans/views/details/utils/patchPlanMappingsData.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/useSaveEffect.ts
Labels: bug

#1179 :soap: Hide empty conditions sections
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesRowExtended.tsx
Labels: kind/cleanup

#1180 Filter migration vms by status
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesList.tsx
Labels: enhancement

#1183 Release v2.6.3
  build/Containerfile
  packages/forklift-console-plugin/package.json
Labels: kind/cleanup
