Repository kubev2v/forklift-console-plugin, pull requests merged in 2024-03, with the labels that each got.

#956 :feet: Align actions to right
  packages/forklift-console-plugin/src/modules/NetworkMaps/actions/NetworkMapActionsDropdown.tsx
  packages/forklift-console-plugin/src/modules/Providers/actions/ProviderActionsDropdown.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/actions/StorageMapActionsDropdown.tsx
Labels: enhancement

#957 :soap: Move inline hooks to utils
  packages/forklift-console-plugin/src/modules/NetworkMaps/componenets/NetworkMapsEmptyState.tsx
  packages/forklift-console-plugin/src/modules/Plans/EmptyStatePlans.tsx
  packages/forklift-console-plugin/src/modules/Plans/PlansPage.tsx
  packages/forklift-console-plugin/src/modules/Plans/data.ts
  packages/forklift-console-plugin/src/modules/StorageMaps/componenets/StorageMapsEmptyState.tsx
  packages/forklift-console-plugin/src/utils/fetch.ts
Labels: kind/cleanup

#958 :soap: Create plan reducer init action
  packages/forklift-console-plugin/src/modules/Providers/utils/components/TableCell/TableLabelCell.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/ProvidersCreateVmMigrationContext.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/ProvidersCreateVmMigrationPage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/actions.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/createInitialState.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/hasMultiplePodNetworkMappings.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/helpers.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/useFetchEffects.ts
Labels: kind/cleanup

#959 🧼 Create plan reducer init action
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/reducer.ts
Labels: kind/cleanup

#960 :soap: Rename migrate button to create migration plan
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/ProviderVirtualMachines.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/components/MigrationAction.tsx
Labels: kind/cleanup

#961 :feet: New plan wizard for the new flow
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/__tests__/PlanRow.test.tsx
  packages/forklift-console-plugin/src/modules/Plans/__tests__/__snapshots__/PlanRow.test.tsx.snap
  packages/forklift-console-plugin/src/modules/Plans/__tests__/mergeData.test.ts
  packages/forklift-console-plugin/src/modules/Plans/__tests__/mergedMockData.json
  packages/forklift-console-plugin/src/modules/Plans/componenets/PlanCriticalConditions.tsx
  packages/forklift-console-plugin/src/modules/Plans/componenets/PlansAddButton.tsx
  packages/forklift-console-plugin/src/modules/Plans/componenets/PlansEmptyState.tsx
  packages/forklift-console-plugin/src/modules/Plans/componenets/index.ts
  packages/forklift-console-plugin/src/modules/Plans/utils/constants/index.ts
  packages/forklift-console-plugin/src/modules/Plans/utils/constants/plan-status.ts
  packages/forklift-console-plugin/src/modules/Plans/utils/helpers/deepCopy.ts
  packages/forklift-console-plugin/src/modules/Plans/utils/helpers/getMigrationPhase.ts
  packages/forklift-console-plugin/src/modules/Plans/utils/helpers/getMigrationVmsCounts.ts
  packages/forklift-console-plugin/src/modules/Plans/utils/helpers/getPhaseLabel.ts
  packages/forklift-console-plugin/src/modules/Plans/utils/helpers/getPlanPhase.ts
  packages/forklift-console-plugin/src/modules/Plans/utils/helpers/getPlanProgressVariant.ts
  packages/forklift-console-plugin/src/modules/Plans/utils/helpers/index.ts
  packages/forklift-console-plugin/src/modules/Plans/utils/index.ts
  packages/forklift-console-plugin/src/modules/Plans/utils/types/MigrationPhase.ts
  packages/forklift-console-plugin/src/modules/Plans/utils/types/PlanData.ts
  packages/forklift-console-plugin/src/modules/Plans/utils/types/PlanPhase.ts
  packages/forklift-console-plugin/src/modules/Plans/utils/types/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/create/PlanCreatePage.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/PlanCreateProgress.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/create/states/PlanCreatePageStore.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/PlanDetailsPage.style.css
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/MigrationsSection/components/MigrationsTable.tsx
  packages/forklift-console-plugin/src/modules/Providers/dynamic-plugin.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/components/MigrationAction.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/ProvidersCreateVmMigrationPage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/components/PlansCreateForm.tsx
Labels: enhancement

#962 :soap: Update badges colors to match patternfly color pallet
  packages/types/src/generated/forklift/constants/NetworkMapModel.v1beta1.ts
  packages/types/src/generated/forklift/constants/PlanModel.v1beta1.ts
  packages/types/src/generated/forklift/constants/ProviderModel.v1beta1.ts
  packages/types/src/generated/forklift/constants/StorageMapModel.v1beta1.ts
Labels: kind/cleanup

#969 :lady_beetle: [MTV-941] Bump bug fix release of node-ip
  package-lock.json
Labels: bug

#970 :lady_beetle: Match is missing in console route
  packages/legacy/src/Plans/components/VMMigrationDetails.tsx
  packages/legacy/src/Plans/components/Wizard/PlanWizard.tsx
  packages/legacy/src/common/components/MustGatherBtn.tsx
Labels: bug

#972 :soap: Increase ulimit
  .github/workflows/on-pull-request.yaml
  ci/build-and-push-images.sh
Labels: kind/ci

#966 :feet: Enrich the mappings tab for the plans details page
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/views/details/PlanDetailsPage.style.css
  packages/forklift-console-plugin/src/modules/Plans/views/details/PlanDetailsPage.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/MappingList.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/MappingListItem.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Mappings/PlanMappings.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Mappings/PlanMappingsSection.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Mappings/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/utils/canDeleteAndPatchPlanMaps.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/utils/constants.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/utils/getInventoryApiUrl.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/utils/getValueByJsonPath.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/utils/hasObjectChangedInGivenFields.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/utils/hasPlanMappingsChanged.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/utils/hasPlanMappingsEditable.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/utils/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/utils/mapMappingsIdsToLabels.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/utils/patchPlanMappingsData.ts
Labels: enhancement

#977 :lady_beetle: Dont cut mapping dropdown
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/MappingListItem.tsx
Labels: bug

#979 :lady_beetle: Set spacing in mapping tab title
  packages/forklift-console-plugin/src/modules/Plans/views/details/PlanDetailsPage.style.css
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Mappings/PlanMappings.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Mappings/PlanMappingsSection.tsx
Labels: bug

#981 :lady_beetle: Fix uneven spacing in mappings tab view mode
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Mappings/PlanMappingsSection.tsx
Labels: bug

#983 :soap: Rename start button to start migration
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/DetailsSection/DetailsSection.tsx
Labels: kind/cleanup

#990 Fix docker/login-action
  .github/workflows/on-push.yaml
Labels: kind/ci

#993 :robot: css indentation linting
  packages/eslint-plugin/stylelintrc.yml
  packages/forklift-console-plugin/src/modules/NetworkMaps/views/details/NetworkMapDetailsPage.style.css
  packages/forklift-console-plugin/src/modules/Overview/views/overview/OverviewPage.style.css
  packages/forklift-console-plugin/src/modules/Plans/views/details/PlanDetailsPage.style.css
  packages/forklift-console-plugin/src/modules/Providers/modals/components/alerts.style.css
  packages/forklift-console-plugin/src/modules/Providers/utils/components/CertificateUpload/CertificateUpload.style.css
  packages/forklift-console-plugin/src/modules/Providers/views/details/ProviderDetailsPage.style.css
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/ProvidersCreateVmMigration.style.css
  packages/forklift-console-plugin/src/modules/StorageMaps/views/details/StorageMapDetailsPage.style.css
Labels: kind/ci

#995 :robot: Action naming
  .github/workflows/on-push-main.yaml
  README.md
Labels: kind/ci

#996 :robot: Clone forkliftci ci script
  ci/deploy-all.sh
  ci/git-clone-forkliftci.sh
Labels: kind/ci

#997 :feet: Enrich the hooks tab for the plans details page - view mode
  package-lock.json
  package.json
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/views/details/PlanDetailsPage.style.css
  packages/forklift-console-plugin/src/modules/Plans/views/details/PlanDetailsPage.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Hooks/PlanHooks.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Hooks/PlanHooksSection.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Hooks/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Mappings/PlanMappingsSection.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/utils/canDeleteAndPatchPlan.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/utils/hasPlanEditable.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/utils/index.ts
Labels: enhancement

#998 :soap: Cleanup build package
  package-lock.json
  packages/webpack/package.json
Labels: kind/cleanup

#999 :soap: Reopen plans vms tab
  packages/forklift-console-plugin/src/modules/Plans/views/details/PlanDetailsPage.tsx
Labels: kind/cleanup

#1000 :feet: Plan details page vms tab
  ci/deploy-kubevirt.sh
  package-lock.json
  packages/common/package.json
  packages/common/src/components-stories/TableView/DefaultHeader.stories.tsx
  packages/common/src/components-stories/TableView/TableView.stories.tsx
  packages/common/src/components/TableView/DefaultHeader.tsx
  packages/common/src/components/TableView/DefaultRow.tsx
  packages/common/src/components/TableView/TableView.tsx
  packages/common/src/components/TableView/Warpers.tsx
  packages/common/src/components/TableView/index.ts
  packages/common/src/components/TableView/types.ts
  packages/common/src/components/TableView/withTr.tsx
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/package.json
  packages/forklift-console-plugin/src/components/page/StandardPage.tsx
  packages/forklift-console-plugin/src/components/page/StandardPageWithSelection.tsx
  packages/forklift-console-plugin/src/components/page/__tests__/StandardPage.test.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/views/details/components/ConditionsSection/ConditionsSection.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/views/list/NetworkMapRow.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/components/PodsTable.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/PlanDetailsPage.style.css
  packages/forklift-console-plugin/src/modules/Plans/views/details/PlanDetailsPage.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/ConditionsSection/ConditionsSection.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/MigrationsSection/components/MigrationsTable.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Hooks/PlanHooksSection.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesRow.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesRowExtended.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Plan/PlanVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Plan/PlanVirtualMachinesRow.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Plan/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/PlanVirtualMachines.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/components/MigrationVMsCancelButton.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/components/NameCellRenderer.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/components/PlanVMsCellProps.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/components/PlanVMsDeleteButton.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/components/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/modals/MigrationVMsCancelModal.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/modals/PlanVMsDeleteModal.style.css
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/modals/PlanVMsDeleteModal.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/modals/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/types/VMData.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/types/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/list/PlanRow.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/list/components/VMsCell.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/list/components/VMsProgressCell.tsx
  packages/forklift-console-plugin/src/modules/Providers/utils/components/TableCell/TableEmptyCell.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/ConditionsSection/ConditionsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/VSphereHostsRow.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Networks/ProviderNetworks.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/OVirtVirtualMachinesRow.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/OpenShiftVirtualMachinesRow.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/OpenStackVirtualMachinesRow.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/OvaVirtualMachinesRow.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/VSphereVirtualMachinesRow.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/ProviderRow.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/views/details/components/ConditionsSection/ConditionsSection.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/views/list/StorageMapRow.tsx
Labels: enhancement

#1001 :lady_beetle: Reduce plan flicker
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/views/details/PlanDetailsPage.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/PlanCriticalCondition.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/PlanPageHeadings.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Details/PlanDetails.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Hooks/PlanHooks.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Mappings/PlanMappings.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Plan/PlanVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/PlanVirtualMachines.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/types/PlanData.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/types/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/YAML/PlanYAML.tsx
Labels: bug

#1002 :feet: Add resource tab to plan details page
  packages/eslint-plugin/cspell.wordlist.txt
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/views/details/PlanDetailsPage.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Resources/OVAPlanResources.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Resources/OpenshiftPlanResources.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Resources/OpenstackPlanResources.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Resources/OvirtPlanResources.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Resources/PlanResources.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Resources/VSpherePlanResources.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Resources/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/index.ts
Labels: enhancement

#1003 :feet: Add simple hooks tab for plans details page
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/utils/helpers/deepCopy.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/PlanDetailsPage.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/SimpleHooks/SimpleHooks.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/SimpleHooks/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/SimpleHooks/state/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/SimpleHooks/state/reducer.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/SimpleHooks/utils/createHook.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/SimpleHooks/utils/deleteHook.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/SimpleHooks/utils/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/SimpleHooks/utils/updateHook.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/index.ts
Labels: enhancement

#1006 :feet: Add jobs to plans vm list
  packages/forklift-console-plugin/src/modules/NetworkMaps/views/details/components/MapsSection/MapsSection.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesRow.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesRowExtended.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Plan/PlanVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/types/VMData.ts
Labels: enhancement

#1007 :soap: Refactor simple plan hook form
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/views/details/PlanDetailsPage.style.css
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/SimpleHooks/SimpleHooks.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/SimpleHooks/hooks/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/SimpleHooks/hooks/usePlanHooks.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/SimpleHooks/utils/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/SimpleHooks/utils/onUpdatePlanHooks.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesRowExtended.tsx
Labels: kind/cleanup

#1008 :soap: Owner ref for plan hooks
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/SimpleHooks/SimpleHooks.tsx
Labels: kind/cleanup

#1011 :robot: Bump webpack dev server
  package-lock.json
  packages/common/package.json
  packages/forklift-console-plugin/package.json
Labels: kind/ci

#1012 :soap: Remove unused hooks directory
  package-lock.json
  package.json
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/NetworkMaps/componenets/NetworkMapsEmptyState.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/utils/helpers/deepCopy.ts
  packages/forklift-console-plugin/src/modules/NetworkMaps/utils/helpers/index.ts
  packages/forklift-console-plugin/src/modules/NetworkMaps/views/details/components/MapsSection/state/reducer.ts
  packages/forklift-console-plugin/src/modules/NetworkMaps/views/details/components/ProvidersSection/state/reducer.ts
  packages/forklift-console-plugin/src/modules/Plans/componenets/PlansEmptyState.tsx
  packages/forklift-console-plugin/src/modules/Plans/utils/helpers/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/PlanDetailsPage.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/ProvidersSection/state/reducer.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Hooks/PlanHooks.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Hooks/PlanHooksSection.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Hooks/hooks/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Hooks/hooks/usePlanHooks.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Hooks/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Hooks/state/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Hooks/state/initialState.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Hooks/state/reducer.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Hooks/utils/createHook.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Hooks/utils/deleteHook.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Hooks/utils/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Hooks/utils/onUpdatePlanHooks.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Hooks/utils/updateHook.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/SimpleHooks/SimpleHooks.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/SimpleHooks/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/index.ts
  packages/forklift-console-plugin/src/modules/Providers/views/list/components/ProvidersEmptyState.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/componenets/StorageMapsEmptyState.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/utils/helpers/deepCopy.ts
  packages/forklift-console-plugin/src/modules/StorageMaps/utils/helpers/index.ts
  packages/forklift-console-plugin/src/modules/StorageMaps/views/details/components/MapsSection/state/reducer.ts
  packages/forklift-console-plugin/src/modules/StorageMaps/views/details/components/ProvidersSection/state/reducer.ts
  packages/forklift-console-plugin/src/utils/constants.ts
  packages/forklift-console-plugin/src/utils/deepCopy.ts
  packages/forklift-console-plugin/src/utils/enums.ts
  packages/forklift-console-plugin/src/utils/index.ts
  packages/forklift-console-plugin/src/utils/resources.ts
  packages/forklift-console-plugin/src/utils/types.ts
Labels: kind/cleanup

#1010 :lady_beetle: Reset dataChanged when entering Edit mode for the Credentials section
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/BaseCredentialsSection.tsx
Labels: bug

#1018 :lady_beetle: Add namepsace to vm when source is OCP
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/OVirtVirtualMachinesRow.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/OvaVirtualMachinesRow.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/VSphereVirtualMachinesRow.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/components/VMCellProps.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/utils/useInventoryVms.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/createInitialState.ts
  packages/forklift-console-plugin/src/utils/resources.ts
Labels: bug

#1020 :lady_beetle: Fix update button spacing
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/views/details/PlanDetailsPage.style.css
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Hooks/PlanHooks.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Mappings/PlanMappings.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Resources/OpenshiftPlanResources.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/BaseCredentialsSection.tsx
Labels: bug

#1022 :lady_beetle: Remember pagination when data change
  packages/common/src/components/Page/__tests__/usePagination.test.tsx
  packages/common/src/components/Page/usePagination.tsx
  packages/forklift-console-plugin/src/components/page/StandardPage.tsx
  packages/forklift-console-plugin/src/components/page/__tests__/StandardPage.test.tsx
  packages/forklift-console-plugin/src/components/page/__tests__/__snapshots__/StandardPage.test.tsx.snap
  packages/forklift-console-plugin/src/modules/NetworkMaps/views/list/NetworkMapsListPage.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Plan/PlanVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/list/PlansListPage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/VSphereHostsList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/components/ProviderVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/ProvidersListPage.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/views/list/StorageMapsListPage.tsx
Labels: bug

#1023 :lady_beetle: Update transfer network help
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/components/TransferNetworkDetailsItem.tsx
Labels: bug

#1026 :lady_beetle: Fix missing source mappings for the OVA provider
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Mappings/PlanMappingsSection.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/utils/mapMappingsIdsToLabels.tsx
  packages/forklift-console-plugin/src/modules/Providers/hooks/useNetworks.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/createInitialState.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/getNetworksUsedBySelectedVMs.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/getStoragesUsedBySelectedVMs.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/mapSourceToLabels.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/reducer.ts
Labels: bug

#1027 :lady_beetle: Avoid displaying a re-generated warning while creating a new mapping
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/helpers.ts
Labels: bug

#1028 :lady_beetle: Openstack resources identified by labels
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/calculateMappings.ts
Labels: bug

#1029 :soap: Refactor provider credentials store
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/BaseCredentialsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/state/index.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/state/reducer.ts
Labels: kind/cleanup

#1032 :lady_beetle: nextSource can be null
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/changeMapping.ts
Labels: bug

#1034 :soap: Separate concerns in vsphere create form
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/vsphere/validateEsxiURL.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/vsphere/validateVCenterURL.ts
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/EditProvider.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/EsxiProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/VCenterProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/index.ts
Labels: kind/cleanup

#1035 :lady_beetle: If one item missing invalidate sum of resources
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Resources/OpenshiftPlanResources.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Resources/OpenstackPlanResources.tsx
Labels: bug

#1040 🐞 migrations may not have an owner
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesList.tsx
Labels: bug

#1037 Work In Progress - MTV-1011: checking and updating links for 2.6 docs
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/cards/SettingsCard.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/EsxiProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/VCenterProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/TransferNetworkDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/TypeDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/URLDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/VDDKDetailsItem.tsx
Labels: kind/documentation

#1042 :lady_beetle: Support validation for the openStack CA certificate field
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenstackCredentialsEdit.tsx
Labels: bug
