Repository kubev2v/forklift-console-plugin, pull requests merged in 2024-11, with the labels that each got.

#1379 Bump kubev2v/types version
  packages/forklift-console-plugin/package.json
  yarn.lock
Labels: kind/cleanup

#1381 Add docs about local NFS, and inotify settings
  README.md
  docs/cli-tools.md
  docs/setup-local-nfs-server.md
Labels: documentation

#1384 MTV-1504 | Add UI for setting inventory memory limits
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Overview/modal/EditInventoryMemoryLimitModal.tsx
  packages/forklift-console-plugin/src/modules/Overview/modal/index.ts
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/cards/SettingsCard.tsx
Labels: enhancement

#1389 For VDDK help text - replace the example with a format
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/vsphere/validateVDDKImage.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/vsphere/vsphereProviderValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/VDDKDetailsItem.tsx
Labels: bug

#1390 For VDDK help text - replace the example with a format - step 2
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderVDDKImage/EditProviderVDDKImage.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/components/ItemIsOwnedAlert.tsx
  packages/forklift-console-plugin/src/modules/Providers/utils/components/VDDKHelperText/VDDKHelperText.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/EsxiProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/VCenterProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/OpenshiftDetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/VDDKDetailsItem.tsx
Labels: bug
