Repository kubev2v/forklift-console-plugin, pull requests merged in 2024-04, with the labels that each got.

#1046 :lady_beetle: Fix plan phase, successfull before warn
  packages/eslint-plugin/cspell.wordlist.txt
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/actions/PlanActionsDropdownItems.tsx
  packages/forklift-console-plugin/src/modules/Plans/hooks/index.ts
  packages/forklift-console-plugin/src/modules/Plans/hooks/usePlanMigration.ts
  packages/forklift-console-plugin/src/modules/Plans/modals/PlanCutoverMigrationModal.style.css
  packages/forklift-console-plugin/src/modules/Plans/modals/PlanCutoverMigrationModal.tsx
  packages/forklift-console-plugin/src/modules/Plans/modals/index.ts
  packages/forklift-console-plugin/src/modules/Plans/utils/helpers/getPlanPhase.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/PlanDetailsPage.style.css
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/DetailsSection/DetailsSection.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/list/components/ActionsCell.tsx
Labels: bug

#1048 :lady_beetle: Avoid wrapping VM concern lables into more than one line
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/components/VMConcernsCellRenderer.tsx
Labels: bug

#1051 Allow to remove faile vms from plan
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Plan/PlanVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/PlanVirtualMachines.tsx
Labels: bug

#1052 :lady_beetle: Validate secret text instead of base64 text
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/EsxiCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/VCenterCredentialsEdit.tsx
Labels: bug

#1053 :lady_beetle: View successful plan vms details
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/PlanVirtualMachines.tsx
Labels: bug

#1055 :lady_beetle: Fix mapping for openstack
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Mappings/PlanMappingsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/hooks/useDisks.ts
  packages/forklift-console-plugin/src/modules/Providers/hooks/useStorages.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/components/MappingListItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/components/PlansCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/calculateMappings.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/createInitialState.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/helpers.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/reducer.ts
  packages/forklift-console-plugin/src/modules/StorageMaps/views/details/components/MapsSection/MapsSection.tsx
Labels: bug

#1047 :lady_beetle: Align Resources tab's table columns by decimal point
  packages/forklift-console-plugin/src/modules/Plans/views/details/PlanDetailsPage.style.css
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Resources/AlignedDecimal.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Resources/OVAPlanResources.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Resources/OpenshiftPlanResources.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Resources/OpenstackPlanResources.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Resources/OvirtPlanResources.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Resources/VSpherePlanResources.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Resources/index.ts
Labels: bug

#1066 :lady_beetle: typo-plane
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/DetailsSection/DetailsSection.tsx
Labels: bug

#1068 :lady_beetle: Check provider type before assuming vm use glance
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/calculateMappings.ts
Labels: api-review

#1070 :lady_beetle: Better compare of inventory changes
  packages/forklift-console-plugin/src/modules/Providers/utils/helpers/hasObjectChangedInGivenFields.ts
Labels: bug

#1072 :lady_beetle: Allow to edit pod network as source
  packages/forklift-console-plugin/src/modules/NetworkMaps/views/details/components/MapsSection/MapsSection.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Mappings/PlanMappingsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/hooks/useNetworks.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/reducer.ts
Labels: bug

#1078 :lady_beetle: Allow to choose same ns on different provider
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/components/PlansCreateForm.tsx
Labels: bug

#1084 :lady_beetle: Alert when mapping is empty
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/components/PlansCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/helpers.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/reducer.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/types.ts
Labels: bug

#1086 :lady_beetle: fix-remove-alerts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/helpers.ts
Labels: bug

#1036 :lady_beetle: Fix few issues with field validations in the vSphere create form
  packages/forklift-console-plugin/src/modules/Providers/utils/helpers/safeBase64Decode.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/openstack/openstackSecretFieldValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/vsphere/esxiSecretFieldValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/vsphere/validateEsxiURL.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/vsphere/validateVCenterURL.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/vsphere/validateVDDKImage.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/vsphere/vcenterSecretFieldValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/EsxiProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/VCenterProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/EsxiCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/VCenterCredentialsEdit.tsx
Labels: bug

#1088 :lady_beetle: Clean vddk image before saving
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderVDDKImage/EditProviderVDDKImage.tsx
Labels: bug

#1092 :robot: Bump github action versions
  .github/workflows/on-pull-request.yaml
  .github/workflows/on-push-main.yaml
  .github/workflows/on-push-release.yaml
Labels: kind/ci

#1093 :feet: Be explicit about host id
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/VSphereHostsList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/VSphereHostsRow.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/components/IDCellRenderer.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/components/index.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/VSphereVirtualMachinesList.tsx
Labels: enhancement

#1094 🐾 Show assessments rather than labels of concerns
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/components/ConcernsTable.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/components/ProviderVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/components/VMConcernsCellRenderer.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/components/index.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/utils/helpers/getCategoryTitle.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/utils/helpers/groupConcernsByCategory.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/utils/helpers/index.ts
Labels: enhancement

#1096 Disable plane edit providers
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/ProvidersSection/ProvidersSection.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/SettingsSection.tsx
Labels: enhancement

#1090 :feet: Add icons to the plan list action buttons
  packages/forklift-console-plugin/src/modules/Plans/views/list/PlansListPage.style.css
  packages/forklift-console-plugin/src/modules/Plans/views/list/components/ActionsCell.tsx
Labels: enhancement

#1104 :soap: Update transltaion file, cleanup unused styles
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/views/list/PlansListPage.style.css
  packages/forklift-console-plugin/src/modules/Plans/views/list/components/ActionsCell.tsx
Labels: kind/cleanup

#1105 :robot: bump to version 2.6.1
  build/Containerfile
  packages/forklift-console-plugin/package.json
Labels: kind/ci

#1110 :robot: Update package lock version
  package-lock.json
Labels: kind/ci

#1114 :soap: Use k8s generic generateName
  package-lock.json
  packages/forklift-console-plugin/package.json
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/createInitialState.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/helpers.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/reducer.ts
Labels: kind/cleanup

#1116 :feet: Update plan phase options
  packages/forklift-console-plugin/src/modules/Plans/utils/constants/plan-status.ts
  packages/forklift-console-plugin/src/modules/Plans/views/list/PlansListPage.tsx
Labels: enhancement

#1111 :lady_beetle: Handle undefined cacert credentials field when copying the field value to clipboard
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/ShowFieldWithClipboardCopy.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/ShowMaskedField.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/list/OpenshiftCredentialsList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/list/OpenstackCredentialsList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/list/OvirtCredentialsList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/list/VSphereCredentialsList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/index.ts
Labels: bug

#1118 :soap: Change plan phases list to explicit id:label list
  packages/forklift-console-plugin/src/modules/Plans/utils/constants/index.ts
  packages/forklift-console-plugin/src/modules/Plans/utils/constants/plan-status.ts
  packages/forklift-console-plugin/src/modules/Plans/utils/constants/planPhases.ts
  packages/forklift-console-plugin/src/modules/Plans/views/list/PlansListPage.tsx
Labels: kind/cleanup

#1119 :soap: Update fields clipboard copy to handle boolean and long texts
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/FieldWithClipboardCopy.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/MaskedField.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/ShowFieldWithClipboardCopy.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/list/Fields.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/list/OpenshiftCredentialsList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/list/OpenstackCredentialsList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/list/OvirtCredentialsList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/list/VSphereCredentialsList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/list/index.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/index.ts
Labels: kind/cleanup

#1120 :soap: If must gather settings is default value of -1 show default
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/cards/SettingsCard.tsx
Labels: kind/cleanup

#1117 Use dynamic validations for providers fields
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/openshift/openshiftSecretFieldValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/openshift/validateOpenshiftURL.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/openstack/openstackSecretFieldValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/openstack/openstackSecretValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/openstack/validateOpenstackURL.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/ova/validateOvaNfsPath.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/ovirt/ovirtSecretFieldValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/ovirt/validateOvirtURL.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/vsphere/esxiSecretFieldValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/vsphere/validateEsxiURL.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/vsphere/validateVCenterURL.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/vsphere/validateVDDKImage.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/vsphere/vcenterSecretFieldValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/EsxiProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/OVAProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/OpenshiftProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/OpenstackProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/OvirtProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/EsxiCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenshiftCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenstackCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenstackCredentialsEditFormGroups/ApplicationCredentialNameSecretFieldsFormGroup.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenstackCredentialsEditFormGroups/ApplicationWithCredentialsIDFormGroup.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenstackCredentialsEditFormGroups/PasswordSecretFieldsFormGroup.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenstackCredentialsEditFormGroups/TokenWithUserIDSecretFieldsFormGroup.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenstackCredentialsEditFormGroups/TokenWithUsernameSecretFieldsFormGroup.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OvirtCredentialsEdit.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/VCenterCredentialsEdit.tsx
Labels: enhancement

#1122 :feet: Enhance the DetailsItem component to enable both hyperlink and edit
  packages/forklift-console-plugin/src/modules/Providers/utils/components/DetailsPage/DetailItem.tsx
Labels: enhancement

#1129 🐾 : Replace vSphere credentials list page with vCenter and Esxi pages
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/EsxiCredentialsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/VCenterCredentialsSection.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/list/EsxiCredentialsList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/list/VCenterCredentialsList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/list/index.ts
Labels: enhancement
