Repository kubev2v/forklift-console-plugin, pull requests merged in 2025-03, with the labels that each got.

#1502 [MTV-2003] Updated text to error message
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/CredentialsSection.tsx
Labels: bug

#1499 Fix a bug for handling a plan creation failures within the plan wizard
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/reducer.ts
Labels: bug

#1462 [MTV-1801] [RFE] Non informative message
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/components/PlanCriticalConditions.tsx
  packages/forklift-console-plugin/src/modules/Plans/components/index.ts
  packages/forklift-console-plugin/src/modules/Plans/utils/types/PlanCondition.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/PlanCriticalCondition.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/PlanPageHeadings.tsx
  packages/forklift-console-plugin/src/modules/Providers/hooks/usePlanSourceProvider.tsx
Labels: bug

#1514 Avoid displaying alert messages for archived plans
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/PlanPageHeadings.tsx
Labels: bug

#1515 Disabling all hooks tab fields in case hooks editing is not allowed
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Hooks/PlanHooks.tsx
Labels: bug

#1517 MTV-2154: Can't create network/storage mappings in 'Create migration plan' page sometimes
  packages/forklift-console-plugin/src/modules/Plans/views/create/PlanCreatePage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/useFetchEffects.ts
Labels: bug

#1516 MTV-1707: Update copy of empty state and tooltip for disabled Add pl…
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/components/PlansAddButton.tsx
  packages/forklift-console-plugin/src/modules/Plans/components/PlansEmptyState.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/list/PlansListPage.tsx
Labels: bug

#1506 [MTV-2016] Add 'Migration type' column to plan list table
  packages/common/src/components/Filter/GroupedEnumFilter.tsx
  packages/common/src/components/Filter/types.ts
  packages/common/src/components/FilterGroup/FilterFromDef.tsx
  packages/common/src/utils/types.ts
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/NetworkMaps/actions/NetworkMapActionsDropdown.tsx
  packages/forklift-console-plugin/src/modules/Plans/utils/constants/migrationTypes.ts
  packages/forklift-console-plugin/src/modules/Plans/utils/helpers/getMigrationType.ts
  packages/forklift-console-plugin/src/modules/Plans/utils/helpers/index.ts
  packages/forklift-console-plugin/src/modules/Plans/utils/types/MigrationType.ts
  packages/forklift-console-plugin/src/modules/Plans/utils/types/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Plan/ActionsCell.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/list/PlanRow.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/list/PlansListPage.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/list/components/ActionsCell.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/list/components/MigrationTypeCell.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/list/components/PlanCell.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/list/components/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/list/constants.ts
  packages/forklift-console-plugin/src/modules/Providers/actions/ProviderActionsDropdown.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/actions/StorageMapActionsDropdown.tsx
Labels: enhancement

#1522 MTV-2026: remove incorrect OVA icon
  packages/forklift-console-plugin/src/components/images/logos.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/ProviderCardItems.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/create/constanats/providerTypes.ts
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/providerCardItems.ts
Labels: bug

#1532 MTV-2266: Avoid displaying the "Host cluster" label for non ocp providers
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/TypeDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/components/ProviderLinkCell.tsx
Labels: bug

#1533 [MTV-1905] Update canceled VM status icon
  packages/forklift-console-plugin/src/modules/Plans/views/list/components/PlanStatusCell.style.scss
  packages/forklift-console-plugin/src/modules/Plans/views/list/components/PlanStatusCell.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/list/components/PlanStatusVmCount.tsx
Labels: bug

#1523 [MTV-1794] Update provider vCenter validation
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/package.json
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderURL/EditProviderURLModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderURL/VSphereEditURLModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/providerValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/vsphere/validateVCenterURL.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/vsphere/vsphereProviderValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/EditProvider.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/VCenterProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/URLDetailsItem.tsx
Labels: bug

#1538 Reset the vSphere VDDK init image field validation and value if 'skip vddk' is checked
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/EsxiProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/VCenterProviderCreateForm.tsx
Labels: bug

#1539 MTV-1901: Avoid double clicking the start migration button within the modal
  packages/forklift-console-plugin/src/modules/Plans/modals/PlanStartMigrationModal.tsx
Labels: bug

#1525 [MTV-2247] Initial new create plan wizard setup
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/package.json
  packages/forklift-console-plugin/src/components/FormErrorHelperText.tsx
  packages/forklift-console-plugin/src/modules/Plans/dynamic-plugin.ts
  packages/forklift-console-plugin/src/modules/Plans/views/create/steps/CreateMigrationPlan/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/components/NameTemplate/utils/utils.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/components/SharedDisksDetailsItem/components/MigrateSharedDisksSwitch/MigrateSharedDisksSwitch.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/components/SharedDisksDetailsItem/utils/helpers.ts
  packages/forklift-console-plugin/src/plans/create/CreatePlanWizard.style.scss
  packages/forklift-console-plugin/src/plans/create/CreatePlanWizard.tsx
  packages/forklift-console-plugin/src/plans/create/CreatePlanWizardFooter.tsx
  packages/forklift-console-plugin/src/plans/create/PlanCreatePage.tsx
  packages/forklift-console-plugin/src/plans/create/constants.ts
  packages/forklift-console-plugin/src/plans/create/steps/GeneralInformationForm.tsx
  packages/forklift-console-plugin/src/plans/create/steps/constants.ts
  packages/forklift-console-plugin/src/utils/docLinks.ts
  packages/forklift-console-plugin/src/utils/helpers.ts
  packages/forklift-console-plugin/tsconfig.json
  yarn.lock
Labels: enhancement

#1505 MTV-2102: Remove storybook
  package.json
  packages/common/.eslintrc.cjs
  packages/common/.storybook/main.ts
  packages/common/.storybook/preview.tsx
  packages/common/package.json
  packages/common/src/components-stories/ExternalLink.stories.ts
  packages/common/src/components-stories/Filter/EnumFilter.stories.tsx
  packages/common/src/components-stories/Filter/FreetextFilter.stories.tsx
  packages/common/src/components-stories/Filter/GroupedEnumFilter.stories.tsx
  packages/common/src/components-stories/Filter/SwitchFilter.stories.ts
  packages/common/src/components-stories/FilterGroup/AttributeValueFilter.stories.tsx
  packages/common/src/components-stories/FilterGroup/FilterGroup.stories.tsx
  packages/common/src/components-stories/FormGroupWithHelpText.stories.tsx
  packages/common/src/components-stories/LoadingDots.stories.ts
  packages/common/src/components-stories/Page/PageStates_BaseState.stories.ts
  packages/common/src/components-stories/Page/PageStates_NoResultsMatchFilter.stories.ts
  packages/common/src/components-stories/RedHatProgressionIcon.stories.ts
  packages/common/src/components-stories/TableView/DefaultHeader.stories.tsx
  packages/common/src/components-stories/TableView/ManageColumnsModal.stories.tsx
  packages/common/src/components-stories/TableView/ManageColumnsToolbarItem.stories.ts
  packages/common/src/components-stories/TableView/TableView.stories.tsx
  packages/common/src/components-stories/assets/github-logo.svg
  packages/common/src/components-stories/console_common.scss
  packages/eslint-plugin/index.js
  yarn.lock
Labels: tech-debt

#1495 MTV-2097: Upgrade react router dom V6/V5 compatible
  packages/forklift-console-plugin/package.json
  packages/forklift-console-plugin/src/components/actions/DropdownItemLink.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/components/NetworkMapsEmptyState.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/views/list/components/StatusCell.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/components/PodsTable.tsx
  packages/forklift-console-plugin/src/modules/Plans/components/PlansEmptyState.tsx
  packages/forklift-console-plugin/src/modules/Plans/modals/ArchiveModal.tsx
  packages/forklift-console-plugin/src/modules/Plans/modals/DuplicateModal.tsx
  packages/forklift-console-plugin/src/modules/Plans/modals/PlanDeleteModal.tsx
  packages/forklift-console-plugin/src/modules/Plans/modals/PlanStartMigrationModal.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesRowExtended.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/list/components/ErrorStatusCell.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/list/components/PlanStatusVmCount.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/list/components/VMsCell.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/list/components/VMsProgressCell.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/DeleteModal/DeleteModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditModal/EditModal.tsx
  packages/forklift-console-plugin/src/modules/Providers/utils/components/DetailsPage/PageHeadings.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/CredentialsDetailsItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Details/ProviderDetails.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/Hosts/components/NameCellRenderer.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/components/OpenshiftNetworkCell.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/components/StatusCell.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/components/VSphereHostCell.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/components/VirtualMachinesCell.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/components/StorageMapsEmptyState.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/views/list/components/StatusCell.tsx
  yarn.lock
Labels: tech-debt

#1540 MTV-2225: Remove rollup
  package.json
  packages/forklift-console-plugin/package.json
  packages/forklift-console-plugin/rollup.config.js
  yarn.lock
Labels: tech-debt

#1498 MTV-1988: Add knip
  knip.json
  package.json
  packages/forklift-console-plugin/jest.config.ts
  packages/forklift-console-plugin/tsconfig.json
  testing/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: tech-debt
