Repository kubev2v/forklift-console-plugin, pull requests merged in 2025-01, with the labels that each got.

#1421 Initilalize the validation value of the 'plan name' field to default instead of error
  packages/forklift-console-plugin/src/modules/Plans/views/create/PlanCreatePage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/reducer.ts
Labels: bug

#1429 Fix a bug of resetting the plan name validation field when resetting the plan
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/reducer.ts
Labels: bug

#1434 MTV-1883: Adding PR template
  .github/pull_request_template.md
Labels: documentation

#1436 [MTV-1880] Move 'Plan name' field to step 1 of create migration plan wizard
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/components/page/StandardPage.style.css
  packages/forklift-console-plugin/src/components/page/StandardPage.tsx
  packages/forklift-console-plugin/src/components/page/StandardPageWithSelection.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/PlanCreatePage.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/PlanCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/PlanNameTextField.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/ProvidersVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/steps/SelectSourceProvider/MemoizedProviderVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/steps/SelectSourceProvider/SelectSourceProvider.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/utils.ts
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/OVirtVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/OpenShiftVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/OpenStackVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/OvaVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/ProviderVirtualMachines.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/VSphereVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/components/ProviderVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/components/PlansCreateForm.tsx
Labels: enhancement

#1430 Migrate deprecated Dropdown component to PF5 and remove ActionServiceDropdown
  packages/common/src/components/ActionServiceDropdown/ActionServiceDropdown.tsx
  packages/common/src/components/ActionServiceDropdown/index.ts
  packages/common/src/components/index.ts
  packages/forklift-console-plugin/src/components/FilterableSelect/FilterableSelect.tsx
  packages/forklift-console-plugin/src/components/actions/DropdownItemLink.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/actions/NetworkMapActionsDropdown.tsx
  packages/forklift-console-plugin/src/modules/NetworkMaps/actions/NetworkMapActionsDropdownItems.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/cards/WelcomeCard.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Metrics/cards/MigrationsChartCard.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Metrics/cards/VmMigrationsChartCard.tsx
  packages/forklift-console-plugin/src/modules/Plans/actions/PlanActionsDropdown.tsx
  packages/forklift-console-plugin/src/modules/Plans/actions/PlanActionsDropdownItems.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/SelectProvider.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/SettingsSection/modals/EditPlanTransferNetwork/EditPlanTransferNetwork.tsx
  packages/forklift-console-plugin/src/modules/Providers/actions/ProviderActionsDropdown.tsx
  packages/forklift-console-plugin/src/modules/Providers/actions/ProviderActionsDropdownItems.tsx
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderDefaultTransferNetwork/EditProviderDefaultTransferNetwork.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/actions/StorageMapActionsDropdown.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/actions/StorageMapActionsDropdownItems.tsx
Labels: enhancement

#1439 [MTV-1905] Canceled VMs are not displayed with status in the plans list
  packages/forklift-console-plugin/src/modules/Plans/views/list/components/PlanStatusCell.tsx
Labels: bug

#1428 Migrate deprecated Wizard component to PF5 and fix Wizard's focus issue
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/utils/helpers/anyValidationErrorExists.ts
  packages/forklift-console-plugin/src/modules/Plans/utils/helpers/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/create/PlanCreatePage.style.css
  packages/forklift-console-plugin/src/modules/Plans/views/create/PlanCreatePage.tsx
Labels: bug, enhancement

#1433 [MTV-1880] Fix 'Project' name select issues
  packages/forklift-console-plugin/src/components/common/ProjectNameSelect.tsx
  packages/forklift-console-plugin/src/components/common/index.ts
  packages/forklift-console-plugin/src/components/index.ts
  packages/forklift-console-plugin/src/modules/Plans/components/PlansAddButton.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/PlanCreatePage.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/PlanCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/ProvidersEmptyState.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/list/PlansListPage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/ProvidersCreatePage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/ProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/components/MigrationAction.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/ProvidersListPage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/list/components/ProvidersAddButton.tsx
Labels: bug

#1435 MTV-1051: Migrate deprecated Select component to PF5, remove unsupported/unused components
  packages/common/src/components-stories/Filter/SearchableEnumFilter.stories.tsx
  packages/common/src/components-stories/Filter/SearchableGroupedEnumFilter.stories.tsx
  packages/common/src/components/Filter/AutocompleteFilter.tsx
  packages/common/src/components/Filter/EnumFilter.tsx
  packages/common/src/components/Filter/GroupedEnumFilter.tsx
  packages/common/src/components/Filter/SearchableEnumFilter.tsx
  packages/common/src/components/Filter/SearchableGroupedEnumFilter.tsx
  packages/common/src/components/Filter/index.ts
  packages/common/src/components/FilterGroup/AttributeValueFilter.tsx
  packages/common/src/components/FilterGroup/matchers.ts
  packages/forklift-console-plugin/src/modules/Overview/modal/SettingsSelectInput.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/create/PlanCreatePage.style.css
  packages/forklift-console-plugin/src/modules/Plans/views/create/components/SelectProvider.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/MappingListItem.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/tabs/VirtualMachines/components/ProviderVirtualMachinesList.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/components/MappingListItem.tsx
Labels: enhancement
