Repository kubev2v/forklift-console-plugin, pull requests merged in 2025-02, with the labels that each got.

#1446 MTV-2002: Fix user access permisisons validation for the plan mappings resources
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/Mappings/PlanMappingsSection.tsx
Labels: bug

#1460 MTV-1791: Add id to openshift (host) storagemaps
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/reducer.ts
Labels: bug

#1458 Update the "Max concurrent vm migrations" field descriptions and links
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Overview/modal/EditMaxVMInFlightModal.tsx
  packages/forklift-console-plugin/src/modules/Overview/views/overview/tabs/Details/cards/SettingsCard.tsx
Labels: bug

#1457 [MTV-2003] Secret is loading message is wrong
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/CredentialsSection.tsx
Labels: bug

#1453 MTV-1727: Provide disabled reason with tooltip on Cancel and Remove VMs buttons
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/components/MigrationVMsCancelButton.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/components/PlanVMsDeleteButton.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/components/VMsActionButton.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/components/index.ts
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/modals/MigrationVMsCancelModal.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/modals/PlanVMsDeleteModal.tsx
Labels: bug

#1447 [MTV-1967] Create plan wizard state is not set correctly when re-selecting a source provider
  packages/forklift-console-plugin/src/modules/Providers/hooks/useProviderInventory.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/useFetchEffects.ts
Labels: bug

#1464 [MTV-1871] Sorting virtual machines isn't saved while refresh
  packages/forklift-console-plugin/src/components/TableSortContext.tsx
  packages/forklift-console-plugin/src/components/page/StandardPage.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesList.tsx
Labels: bug

#1466 [MTV-2013] Cant create provider on D/S
  README.md
  ci/configure/openshift.sh
  ci/deploy-all.sh
  packages/common/README.md
  packages/forklift-console-plugin/environment-defaults.ts
  packages/forklift-console-plugin/src/__mocks__/envvars.ts
  packages/forklift-console-plugin/src/components/common/ProjectNameSelect.tsx
  packages/forklift-console-plugin/src/components/empty-states/images/globals.d.ts
  packages/forklift-console-plugin/src/modules/Plans/views/create/PlanCreatePage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/ProvidersCreatePage.tsx
  packages/forklift-console-plugin/src/utils/constants.ts
  packages/forklift-console-plugin/src/utils/env.ts
  packages/forklift-console-plugin/src/utils/namespaces.ts
  packages/forklift-console-plugin/webpack.config.ts
Labels: bug

#1469 [MTV-2052] Plan create wizard - auto calculated mapping for a plan is not displayed in 2nd step page anymore
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/actions.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/reducer.ts
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/useFetchEffects.ts
Labels: bug

#1459 Replace VDDK image hint sections with rephrased warning alert sections
  packages/forklift-console-plugin/locales/en/plugin__forklift-console-plugin.json
  packages/forklift-console-plugin/src/modules/Providers/modals/EditProviderVDDKImage/EditProviderVDDKImage.tsx
  packages/forklift-console-plugin/src/modules/Providers/utils/components/VDDKHelperText/VDDKHelperText.tsx
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/vsphere/validateVDDKImage.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/vsphere/vsphereProviderValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/EsxiProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/VCenterProviderCreateForm.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/DetailsSection/components/VDDKDetailsItem.tsx
Labels: enhancement

#1477 [MTV-2063] Create plan wizard - a plan can't be created
  packages/forklift-console-plugin/src/modules/Providers/views/migrate/reducer/reducer.ts
Labels: bug

#1478 [MTV-1788] Failed to create OSP provider with authentication type - token and username
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenstackCredentialsEditFormGroups/ApplicationCredentialNameSecretFieldsFormGroup.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenstackCredentialsEditFormGroups/ApplicationWithCredentialsIDFormGroup.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenstackCredentialsEditFormGroups/PasswordSecretFieldsFormGroup.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenstackCredentialsEditFormGroups/TokenWithUserIDSecretFieldsFormGroup.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenstackCredentialsEditFormGroups/TokenWithUsernameSecretFieldsFormGroup.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/edit/OpenstackCredentialsEditFormGroups/constants.ts
Labels: bug

#1476 Avoid displaying double vertical scrollbars for plan's wizard
  packages/forklift-console-plugin/src/modules/Plans/views/create/PlanCreatePage.tsx
Labels: bug

#1471 MTV-2022: Remove Start/Restart migration button from plan details header
  packages/forklift-console-plugin/src/modules/Plans/views/details/components/PlanPageHeadings.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/list/components/PlanStatusCell.tsx
Labels: bug

#1454 Avoid running more than one migration concurrently
  packages/forklift-console-plugin/src/modules/Plans/actions/PlanActionsDropdownItems.tsx
  packages/forklift-console-plugin/src/modules/Plans/modals/PlanStartMigrationModal.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/list/components/PlanStatusCell.tsx
Labels: bug

#1487 When migration task isn't completed but task's progress.total equals completed, mark task as successful
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesRow.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/tabs/VirtualMachines/Migration/MigrationVirtualMachinesRowExtended.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/utils/hasPipelineCompleted.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/utils/hasPipelineNotFailed.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/utils/hasTaskCompleted.tsx
  packages/forklift-console-plugin/src/modules/Plans/views/details/utils/index.ts
Labels: bug

#1488 Fix few create/edit provider fields validators bugs
  packages/forklift-console-plugin/src/modules/Providers/utils/helpers/validateUrlAndTokenExistence.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/openshift/openshiftProviderValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/openshift/openshiftSecretValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/providerAndSecretValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/providerValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/secretValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/views/create/ProvidersCreatePage.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/details/components/CredentialsSection/components/BaseCredentialsSection.tsx
Labels: bug

#1491 Fix StorageMaps, NetworkMaps pages for referring to mapping's source/destination providers based on provider names
  packages/forklift-console-plugin/src/modules/NetworkMaps/views/details/components/MapsSection/MapsSection.tsx
  packages/forklift-console-plugin/src/modules/StorageMaps/views/details/components/MapsSection/MapsSection.tsx
Labels: bug

#1475 [MTV-1794] Add warning when specifying IP for a secure provider
  packages/forklift-console-plugin/package.json
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/common.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/providerValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/vsphere/validateVCenterURL.ts
  packages/forklift-console-plugin/src/modules/Providers/utils/validators/provider/vsphere/vsphereProviderValidator.ts
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/EditProvider.tsx
  packages/forklift-console-plugin/src/modules/Providers/views/create/components/VCenterProviderCreateForm.tsx
Labels: bug, enhancement
